// Package adminapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package adminapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// Defines values for CreatePresignedUrlRequestContentType.
const (
	Imagejpeg CreatePresignedUrlRequestContentType = "image/jpeg"
	Imagepng  CreatePresignedUrlRequestContentType = "image/png"
)

// Valid indicates whether the value is a known member of the CreatePresignedUrlRequestContentType enum.
func (e CreatePresignedUrlRequestContentType) Valid() bool {
	switch e {
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	default:
		return false
	}
}

// Defines values for CreateQuestionRequestType.
const (
	CreateQuestionRequestTypeSingleChoice CreateQuestionRequestType = "single_choice"
)

// Valid indicates whether the value is a known member of the CreateQuestionRequestType enum.
func (e CreateQuestionRequestType) Valid() bool {
	switch e {
	case CreateQuestionRequestTypeSingleChoice:
		return true
	default:
		return false
	}
}

// Defines values for QuestionType.
const (
	QuestionTypeSingleChoice QuestionType = "single_choice"
)

// Valid indicates whether the value is a known member of the QuestionType enum.
func (e QuestionType) Valid() bool {
	switch e {
	case QuestionTypeSingleChoice:
		return true
	default:
		return false
	}
}

// Defines values for UpdateQuestionRequestType.
const (
	SingleChoice UpdateQuestionRequestType = "single_choice"
)

// Valid indicates whether the value is a known member of the UpdateQuestionRequestType enum.
func (e UpdateQuestionRequestType) Valid() bool {
	switch e {
	case SingleChoice:
		return true
	default:
		return false
	}
}

// CategoriesResponse defines model for CategoriesResponse.
type CategoriesResponse struct {
	Categories []Category `json:"categories"`
	Total      int        `json:"total"`
}

// Category defines model for Category.
type Category struct {
	Description   *string `json:"description,omitempty"`
	Id            int64   `json:"id"`
	Title         string  `json:"title"`
	WorkbookCount *int    `json:"workbookCount,omitempty"`
}

// CategoryDetail defines model for CategoryDetail.
type CategoryDetail struct {
	Description *string    `json:"description,omitempty"`
	Id          int64      `json:"id"`
	Title       string     `json:"title"`
	Workbooks   []Workbook `json:"workbooks"`
}

// Choice defines model for Choice.
type Choice struct {
	IsCorrect bool   `json:"isCorrect"`
	Text      string `json:"text"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
}

// CreatePresignedUrlRequest defines model for CreatePresignedUrlRequest.
type CreatePresignedUrlRequest struct {
	ContentType CreatePresignedUrlRequestContentType `json:"contentType"`
	Filename    string                               `json:"filename"`
}

// CreatePresignedUrlRequestContentType defines model for CreatePresignedUrlRequest.ContentType.
type CreatePresignedUrlRequestContentType string

// CreateQuestionRequest defines model for CreateQuestionRequest.
type CreateQuestionRequest struct {
	Choices     []Choice                  `json:"choices"`
	Explanation *string                   `json:"explanation,omitempty"`
	ImageIds    *[]int64                  `json:"imageIds,omitempty"`
	Text        string                    `json:"text"`
	Type        CreateQuestionRequestType `json:"type"`
}

// CreateQuestionRequestType defines model for CreateQuestionRequest.Type.
type CreateQuestionRequestType string

// CreateWorkbookRequest defines model for CreateWorkbookRequest.
type CreateWorkbookRequest struct {
	CategoryId  *int64   `json:"categoryId,omitempty"`
	Description *string  `json:"description,omitempty"`
	QuestionIds *[]int64 `json:"questionIds,omitempty"`
	Title       string   `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// PresignedUrlResponse defines model for PresignedUrlResponse.
type PresignedUrlResponse struct {
	CdnUrl    string `json:"cdnUrl"`
	ImageId   int64  `json:"imageId"`
	UploadUrl string `json:"uploadUrl"`
}

// PublishResponse defines model for PublishResponse.
type PublishResponse struct {
	CategoriesCount *int      `json:"categoriesCount,omitempty"`
	Message         string    `json:"message"`
	PublishedAt     time.Time `json:"publishedAt"`
	WorkbooksCount  *int      `json:"workbooksCount,omitempty"`
}

// Question defines model for Question.
type Question struct {
	Choices     []Choice     `json:"choices"`
	Explanation *string      `json:"explanation,omitempty"`
	Id          int64        `json:"id"`
	Images      *[]string    `json:"images,omitempty"`
	Text        string       `json:"text"`
	Type        QuestionType `json:"type"`
}

// QuestionType defines model for Question.Type.
type QuestionType string

// QuestionsResponse defines model for QuestionsResponse.
type QuestionsResponse struct {
	Questions []Question `json:"questions"`
	Total     int        `json:"total"`
}

// UpdateCategoryRequest defines model for UpdateCategoryRequest.
type UpdateCategoryRequest struct {
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
}

// UpdateQuestionRequest defines model for UpdateQuestionRequest.
type UpdateQuestionRequest struct {
	Choices     []Choice                  `json:"choices"`
	Explanation *string                   `json:"explanation,omitempty"`
	ImageIds    *[]int64                  `json:"imageIds,omitempty"`
	Text        string                    `json:"text"`
	Type        UpdateQuestionRequestType `json:"type"`
}

// UpdateQuestionRequestType defines model for UpdateQuestionRequest.Type.
type UpdateQuestionRequestType string

// UpdateWorkbookRequest defines model for UpdateWorkbookRequest.
type UpdateWorkbookRequest struct {
	CategoryId  *int64   `json:"categoryId,omitempty"`
	Description *string  `json:"description,omitempty"`
	QuestionIds *[]int64 `json:"questionIds,omitempty"`
	Title       string   `json:"title"`
}

// User defines model for User.
type User struct {
	CreatedAt  time.Time `json:"createdAt"`
	Id         int64     `json:"id"`
	IdentityId string    `json:"identityId"`
}

// UsersResponse defines model for UsersResponse.
type UsersResponse struct {
	Total int    `json:"total"`
	Users []User `json:"users"`
}

// Workbook defines model for Workbook.
type Workbook struct {
	CategoryId    *int64  `json:"categoryId,omitempty"`
	Description   *string `json:"description,omitempty"`
	Id            int64   `json:"id"`
	QuestionCount *int    `json:"questionCount,omitempty"`
	Title         string  `json:"title"`
}

// WorkbookDetail defines model for WorkbookDetail.
type WorkbookDetail struct {
	CategoryId  *int64     `json:"categoryId,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          int64      `json:"id"`
	Questions   []Question `json:"questions"`
	Title       string     `json:"title"`
}

// WorkbooksResponse defines model for WorkbooksResponse.
type WorkbooksResponse struct {
	Total     int        `json:"total"`
	Workbooks []Workbook `json:"workbooks"`
}

// GetCategoriesParams defines parameters for GetCategories.
type GetCategoriesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetQuestionsParams defines parameters for GetQuestions.
type GetQuestionsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetWorkbooksParams defines parameters for GetWorkbooks.
type GetWorkbooksParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CreateCategoryRequest

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = UpdateCategoryRequest

// CreatePresignedUrlJSONRequestBody defines body for CreatePresignedUrl for application/json ContentType.
type CreatePresignedUrlJSONRequestBody = CreatePresignedUrlRequest

// CreateQuestionJSONRequestBody defines body for CreateQuestion for application/json ContentType.
type CreateQuestionJSONRequestBody = CreateQuestionRequest

// UpdateQuestionJSONRequestBody defines body for UpdateQuestion for application/json ContentType.
type UpdateQuestionJSONRequestBody = UpdateQuestionRequest

// CreateWorkbookJSONRequestBody defines body for CreateWorkbook for application/json ContentType.
type CreateWorkbookJSONRequestBody = CreateWorkbookRequest

// UpdateWorkbookJSONRequestBody defines body for UpdateWorkbook for application/json ContentType.
type UpdateWorkbookJSONRequestBody = UpdateWorkbookRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ルート
	// (GET /)
	Root(ctx echo.Context) error
	// カテゴリ一覧取得
	// (GET /categories)
	GetCategories(ctx echo.Context, params GetCategoriesParams) error
	// カテゴリ作成
	// (POST /categories)
	CreateCategory(ctx echo.Context) error
	// カテゴリ削除
	// (DELETE /categories/{categoryId})
	DeleteCategory(ctx echo.Context, categoryId int64) error
	// カテゴリ取得
	// (GET /categories/{categoryId})
	GetCategory(ctx echo.Context, categoryId int64) error
	// カテゴリ更新
	// (PUT /categories/{categoryId})
	UpdateCategory(ctx echo.Context, categoryId int64) error
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// 画像アップロード用Presigned URL発行
	// (POST /images/presigned-url)
	CreatePresignedUrl(ctx echo.Context) error
	// コンテンツをS3にJSON書き出し
	// (POST /publish)
	PostPublish(ctx echo.Context) error
	// 問題一覧取得
	// (GET /questions)
	GetQuestions(ctx echo.Context, params GetQuestionsParams) error
	// 問題作成
	// (POST /questions)
	CreateQuestion(ctx echo.Context) error
	// 問題削除
	// (DELETE /questions/{questionId})
	DeleteQuestion(ctx echo.Context, questionId int64) error
	// 問題取得
	// (GET /questions/{questionId})
	GetQuestion(ctx echo.Context, questionId int64) error
	// 問題更新
	// (PUT /questions/{questionId})
	UpdateQuestion(ctx echo.Context, questionId int64) error
	// ユーザー一覧取得
	// (GET /users)
	GetUsers(ctx echo.Context, params GetUsersParams) error
	// 問題集一覧取得
	// (GET /workbooks)
	GetWorkbooks(ctx echo.Context, params GetWorkbooksParams) error
	// 問題集作成
	// (POST /workbooks)
	CreateWorkbook(ctx echo.Context) error
	// 問題集削除
	// (DELETE /workbooks/{workbookId})
	DeleteWorkbook(ctx echo.Context, workbookId int64) error
	// 問題集取得
	// (GET /workbooks/{workbookId})
	GetWorkbook(ctx echo.Context, workbookId int64) error
	// 問題集更新
	// (PUT /workbooks/{workbookId})
	UpdateWorkbook(ctx echo.Context, workbookId int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Root converts echo context to params.
func (w *ServerInterfaceWrapper) Root(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Root(ctx)
	return err
}

// GetCategories converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategories(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCategoriesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategories(ctx, params)
	return err
}

// CreateCategory converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCategory(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCategory(ctx)
	return err
}

// DeleteCategory converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCategory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "categoryId" -------------
	var categoryId int64

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", ctx.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCategory(ctx, categoryId)
	return err
}

// GetCategory converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "categoryId" -------------
	var categoryId int64

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", ctx.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategory(ctx, categoryId)
	return err
}

// UpdateCategory converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateCategory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "categoryId" -------------
	var categoryId int64

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", ctx.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateCategory(ctx, categoryId)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// CreatePresignedUrl converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePresignedUrl(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePresignedUrl(ctx)
	return err
}

// PostPublish converts echo context to params.
func (w *ServerInterfaceWrapper) PostPublish(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPublish(ctx)
	return err
}

// GetQuestions converts echo context to params.
func (w *ServerInterfaceWrapper) GetQuestions(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetQuestionsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetQuestions(ctx, params)
	return err
}

// CreateQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) CreateQuestion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateQuestion(ctx)
	return err
}

// DeleteQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteQuestion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "questionId" -------------
	var questionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", ctx.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter questionId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteQuestion(ctx, questionId)
	return err
}

// GetQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) GetQuestion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "questionId" -------------
	var questionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", ctx.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter questionId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetQuestion(ctx, questionId)
	return err
}

// UpdateQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateQuestion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "questionId" -------------
	var questionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", ctx.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter questionId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateQuestion(ctx, questionId)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsers(ctx, params)
	return err
}

// GetWorkbooks converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkbooks(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkbooksParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkbooks(ctx, params)
	return err
}

// CreateWorkbook converts echo context to params.
func (w *ServerInterfaceWrapper) CreateWorkbook(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateWorkbook(ctx)
	return err
}

// DeleteWorkbook converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteWorkbook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "workbookId" -------------
	var workbookId int64

	err = runtime.BindStyledParameterWithOptions("simple", "workbookId", ctx.Param("workbookId"), &workbookId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter workbookId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteWorkbook(ctx, workbookId)
	return err
}

// GetWorkbook converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkbook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "workbookId" -------------
	var workbookId int64

	err = runtime.BindStyledParameterWithOptions("simple", "workbookId", ctx.Param("workbookId"), &workbookId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter workbookId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkbook(ctx, workbookId)
	return err
}

// UpdateWorkbook converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateWorkbook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "workbookId" -------------
	var workbookId int64

	err = runtime.BindStyledParameterWithOptions("simple", "workbookId", ctx.Param("workbookId"), &workbookId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter workbookId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateWorkbook(ctx, workbookId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/", wrapper.Root)
	router.GET(baseURL+"/categories", wrapper.GetCategories)
	router.POST(baseURL+"/categories", wrapper.CreateCategory)
	router.DELETE(baseURL+"/categories/:categoryId", wrapper.DeleteCategory)
	router.GET(baseURL+"/categories/:categoryId", wrapper.GetCategory)
	router.PUT(baseURL+"/categories/:categoryId", wrapper.UpdateCategory)
	router.GET(baseURL+"/health", wrapper.HealthCheck)
	router.POST(baseURL+"/images/presigned-url", wrapper.CreatePresignedUrl)
	router.POST(baseURL+"/publish", wrapper.PostPublish)
	router.GET(baseURL+"/questions", wrapper.GetQuestions)
	router.POST(baseURL+"/questions", wrapper.CreateQuestion)
	router.DELETE(baseURL+"/questions/:questionId", wrapper.DeleteQuestion)
	router.GET(baseURL+"/questions/:questionId", wrapper.GetQuestion)
	router.PUT(baseURL+"/questions/:questionId", wrapper.UpdateQuestion)
	router.GET(baseURL+"/users", wrapper.GetUsers)
	router.GET(baseURL+"/workbooks", wrapper.GetWorkbooks)
	router.POST(baseURL+"/workbooks", wrapper.CreateWorkbook)
	router.DELETE(baseURL+"/workbooks/:workbookId", wrapper.DeleteWorkbook)
	router.GET(baseURL+"/workbooks/:workbookId", wrapper.GetWorkbook)
	router.PUT(baseURL+"/workbooks/:workbookId", wrapper.UpdateWorkbook)

}

type RootRequestObject struct {
}

type RootResponseObject interface {
	VisitRootResponse(w http.ResponseWriter) error
}

type Root200JSONResponse MessageResponse

func (response Root200JSONResponse) VisitRootResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesRequestObject struct {
	Params GetCategoriesParams
}

type GetCategoriesResponseObject interface {
	VisitGetCategoriesResponse(w http.ResponseWriter) error
}

type GetCategories200JSONResponse CategoriesResponse

func (response GetCategories200JSONResponse) VisitGetCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCategories400JSONResponse Error

func (response GetCategories400JSONResponse) VisitGetCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateCategoryRequestObject struct {
	Body *CreateCategoryJSONRequestBody
}

type CreateCategoryResponseObject interface {
	VisitCreateCategoryResponse(w http.ResponseWriter) error
}

type CreateCategory201JSONResponse CategoryDetail

func (response CreateCategory201JSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateCategory400JSONResponse Error

func (response CreateCategory400JSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCategoryRequestObject struct {
	CategoryId int64 `json:"categoryId"`
}

type DeleteCategoryResponseObject interface {
	VisitDeleteCategoryResponse(w http.ResponseWriter) error
}

type DeleteCategory204Response struct {
}

func (response DeleteCategory204Response) VisitDeleteCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCategory404JSONResponse Error

func (response DeleteCategory404JSONResponse) VisitDeleteCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoryRequestObject struct {
	CategoryId int64 `json:"categoryId"`
}

type GetCategoryResponseObject interface {
	VisitGetCategoryResponse(w http.ResponseWriter) error
}

type GetCategory200JSONResponse CategoryDetail

func (response GetCategory200JSONResponse) VisitGetCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCategory404JSONResponse Error

func (response GetCategory404JSONResponse) VisitGetCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCategoryRequestObject struct {
	CategoryId int64 `json:"categoryId"`
	Body       *UpdateCategoryJSONRequestBody
}

type UpdateCategoryResponseObject interface {
	VisitUpdateCategoryResponse(w http.ResponseWriter) error
}

type UpdateCategory200JSONResponse CategoryDetail

func (response UpdateCategory200JSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCategory400JSONResponse Error

func (response UpdateCategory400JSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCategory404JSONResponse Error

func (response UpdateCategory404JSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthResponse

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresignedUrlRequestObject struct {
	Body *CreatePresignedUrlJSONRequestBody
}

type CreatePresignedUrlResponseObject interface {
	VisitCreatePresignedUrlResponse(w http.ResponseWriter) error
}

type CreatePresignedUrl200JSONResponse PresignedUrlResponse

func (response CreatePresignedUrl200JSONResponse) VisitCreatePresignedUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresignedUrl400JSONResponse Error

func (response CreatePresignedUrl400JSONResponse) VisitCreatePresignedUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostPublishRequestObject struct {
}

type PostPublishResponseObject interface {
	VisitPostPublishResponse(w http.ResponseWriter) error
}

type PostPublish200JSONResponse PublishResponse

func (response PostPublish200JSONResponse) VisitPostPublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostPublish500JSONResponse Error

func (response PostPublish500JSONResponse) VisitPostPublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestionsRequestObject struct {
	Params GetQuestionsParams
}

type GetQuestionsResponseObject interface {
	VisitGetQuestionsResponse(w http.ResponseWriter) error
}

type GetQuestions200JSONResponse QuestionsResponse

func (response GetQuestions200JSONResponse) VisitGetQuestionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestions400JSONResponse Error

func (response GetQuestions400JSONResponse) VisitGetQuestionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateQuestionRequestObject struct {
	Body *CreateQuestionJSONRequestBody
}

type CreateQuestionResponseObject interface {
	VisitCreateQuestionResponse(w http.ResponseWriter) error
}

type CreateQuestion201JSONResponse Question

func (response CreateQuestion201JSONResponse) VisitCreateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateQuestion400JSONResponse Error

func (response CreateQuestion400JSONResponse) VisitCreateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteQuestionRequestObject struct {
	QuestionId int64 `json:"questionId"`
}

type DeleteQuestionResponseObject interface {
	VisitDeleteQuestionResponse(w http.ResponseWriter) error
}

type DeleteQuestion204Response struct {
}

func (response DeleteQuestion204Response) VisitDeleteQuestionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteQuestion404JSONResponse Error

func (response DeleteQuestion404JSONResponse) VisitDeleteQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestionRequestObject struct {
	QuestionId int64 `json:"questionId"`
}

type GetQuestionResponseObject interface {
	VisitGetQuestionResponse(w http.ResponseWriter) error
}

type GetQuestion200JSONResponse Question

func (response GetQuestion200JSONResponse) VisitGetQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestion404JSONResponse Error

func (response GetQuestion404JSONResponse) VisitGetQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateQuestionRequestObject struct {
	QuestionId int64 `json:"questionId"`
	Body       *UpdateQuestionJSONRequestBody
}

type UpdateQuestionResponseObject interface {
	VisitUpdateQuestionResponse(w http.ResponseWriter) error
}

type UpdateQuestion200JSONResponse Question

func (response UpdateQuestion200JSONResponse) VisitUpdateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateQuestion400JSONResponse Error

func (response UpdateQuestion400JSONResponse) VisitUpdateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateQuestion404JSONResponse Error

func (response UpdateQuestion404JSONResponse) VisitUpdateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersRequestObject struct {
	Params GetUsersParams
}

type GetUsersResponseObject interface {
	VisitGetUsersResponse(w http.ResponseWriter) error
}

type GetUsers200JSONResponse UsersResponse

func (response GetUsers200JSONResponse) VisitGetUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsers400JSONResponse Error

func (response GetUsers400JSONResponse) VisitGetUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbooksRequestObject struct {
	Params GetWorkbooksParams
}

type GetWorkbooksResponseObject interface {
	VisitGetWorkbooksResponse(w http.ResponseWriter) error
}

type GetWorkbooks200JSONResponse WorkbooksResponse

func (response GetWorkbooks200JSONResponse) VisitGetWorkbooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbooks400JSONResponse Error

func (response GetWorkbooks400JSONResponse) VisitGetWorkbooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkbookRequestObject struct {
	Body *CreateWorkbookJSONRequestBody
}

type CreateWorkbookResponseObject interface {
	VisitCreateWorkbookResponse(w http.ResponseWriter) error
}

type CreateWorkbook201JSONResponse WorkbookDetail

func (response CreateWorkbook201JSONResponse) VisitCreateWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkbook400JSONResponse Error

func (response CreateWorkbook400JSONResponse) VisitCreateWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteWorkbookRequestObject struct {
	WorkbookId int64 `json:"workbookId"`
}

type DeleteWorkbookResponseObject interface {
	VisitDeleteWorkbookResponse(w http.ResponseWriter) error
}

type DeleteWorkbook204Response struct {
}

func (response DeleteWorkbook204Response) VisitDeleteWorkbookResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteWorkbook404JSONResponse Error

func (response DeleteWorkbook404JSONResponse) VisitDeleteWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbookRequestObject struct {
	WorkbookId int64 `json:"workbookId"`
}

type GetWorkbookResponseObject interface {
	VisitGetWorkbookResponse(w http.ResponseWriter) error
}

type GetWorkbook200JSONResponse WorkbookDetail

func (response GetWorkbook200JSONResponse) VisitGetWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbook404JSONResponse Error

func (response GetWorkbook404JSONResponse) VisitGetWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWorkbookRequestObject struct {
	WorkbookId int64 `json:"workbookId"`
	Body       *UpdateWorkbookJSONRequestBody
}

type UpdateWorkbookResponseObject interface {
	VisitUpdateWorkbookResponse(w http.ResponseWriter) error
}

type UpdateWorkbook200JSONResponse WorkbookDetail

func (response UpdateWorkbook200JSONResponse) VisitUpdateWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWorkbook400JSONResponse Error

func (response UpdateWorkbook400JSONResponse) VisitUpdateWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWorkbook404JSONResponse Error

func (response UpdateWorkbook404JSONResponse) VisitUpdateWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ルート
	// (GET /)
	Root(ctx context.Context, request RootRequestObject) (RootResponseObject, error)
	// カテゴリ一覧取得
	// (GET /categories)
	GetCategories(ctx context.Context, request GetCategoriesRequestObject) (GetCategoriesResponseObject, error)
	// カテゴリ作成
	// (POST /categories)
	CreateCategory(ctx context.Context, request CreateCategoryRequestObject) (CreateCategoryResponseObject, error)
	// カテゴリ削除
	// (DELETE /categories/{categoryId})
	DeleteCategory(ctx context.Context, request DeleteCategoryRequestObject) (DeleteCategoryResponseObject, error)
	// カテゴリ取得
	// (GET /categories/{categoryId})
	GetCategory(ctx context.Context, request GetCategoryRequestObject) (GetCategoryResponseObject, error)
	// カテゴリ更新
	// (PUT /categories/{categoryId})
	UpdateCategory(ctx context.Context, request UpdateCategoryRequestObject) (UpdateCategoryResponseObject, error)
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// 画像アップロード用Presigned URL発行
	// (POST /images/presigned-url)
	CreatePresignedUrl(ctx context.Context, request CreatePresignedUrlRequestObject) (CreatePresignedUrlResponseObject, error)
	// コンテンツをS3にJSON書き出し
	// (POST /publish)
	PostPublish(ctx context.Context, request PostPublishRequestObject) (PostPublishResponseObject, error)
	// 問題一覧取得
	// (GET /questions)
	GetQuestions(ctx context.Context, request GetQuestionsRequestObject) (GetQuestionsResponseObject, error)
	// 問題作成
	// (POST /questions)
	CreateQuestion(ctx context.Context, request CreateQuestionRequestObject) (CreateQuestionResponseObject, error)
	// 問題削除
	// (DELETE /questions/{questionId})
	DeleteQuestion(ctx context.Context, request DeleteQuestionRequestObject) (DeleteQuestionResponseObject, error)
	// 問題取得
	// (GET /questions/{questionId})
	GetQuestion(ctx context.Context, request GetQuestionRequestObject) (GetQuestionResponseObject, error)
	// 問題更新
	// (PUT /questions/{questionId})
	UpdateQuestion(ctx context.Context, request UpdateQuestionRequestObject) (UpdateQuestionResponseObject, error)
	// ユーザー一覧取得
	// (GET /users)
	GetUsers(ctx context.Context, request GetUsersRequestObject) (GetUsersResponseObject, error)
	// 問題集一覧取得
	// (GET /workbooks)
	GetWorkbooks(ctx context.Context, request GetWorkbooksRequestObject) (GetWorkbooksResponseObject, error)
	// 問題集作成
	// (POST /workbooks)
	CreateWorkbook(ctx context.Context, request CreateWorkbookRequestObject) (CreateWorkbookResponseObject, error)
	// 問題集削除
	// (DELETE /workbooks/{workbookId})
	DeleteWorkbook(ctx context.Context, request DeleteWorkbookRequestObject) (DeleteWorkbookResponseObject, error)
	// 問題集取得
	// (GET /workbooks/{workbookId})
	GetWorkbook(ctx context.Context, request GetWorkbookRequestObject) (GetWorkbookResponseObject, error)
	// 問題集更新
	// (PUT /workbooks/{workbookId})
	UpdateWorkbook(ctx context.Context, request UpdateWorkbookRequestObject) (UpdateWorkbookResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Root operation middleware
func (sh *strictHandler) Root(ctx echo.Context) error {
	var request RootRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Root(ctx.Request().Context(), request.(RootRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Root")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RootResponseObject); ok {
		return validResponse.VisitRootResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCategories operation middleware
func (sh *strictHandler) GetCategories(ctx echo.Context, params GetCategoriesParams) error {
	var request GetCategoriesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategories(ctx.Request().Context(), request.(GetCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCategoriesResponseObject); ok {
		return validResponse.VisitGetCategoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateCategory operation middleware
func (sh *strictHandler) CreateCategory(ctx echo.Context) error {
	var request CreateCategoryRequestObject

	var body CreateCategoryJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCategory(ctx.Request().Context(), request.(CreateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateCategoryResponseObject); ok {
		return validResponse.VisitCreateCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteCategory operation middleware
func (sh *strictHandler) DeleteCategory(ctx echo.Context, categoryId int64) error {
	var request DeleteCategoryRequestObject

	request.CategoryId = categoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCategory(ctx.Request().Context(), request.(DeleteCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteCategoryResponseObject); ok {
		return validResponse.VisitDeleteCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCategory operation middleware
func (sh *strictHandler) GetCategory(ctx echo.Context, categoryId int64) error {
	var request GetCategoryRequestObject

	request.CategoryId = categoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategory(ctx.Request().Context(), request.(GetCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCategoryResponseObject); ok {
		return validResponse.VisitGetCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateCategory operation middleware
func (sh *strictHandler) UpdateCategory(ctx echo.Context, categoryId int64) error {
	var request UpdateCategoryRequestObject

	request.CategoryId = categoryId

	var body UpdateCategoryJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCategory(ctx.Request().Context(), request.(UpdateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateCategoryResponseObject); ok {
		return validResponse.VisitUpdateCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(ctx echo.Context) error {
	var request HealthCheckRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx.Request().Context(), request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		return validResponse.VisitHealthCheckResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreatePresignedUrl operation middleware
func (sh *strictHandler) CreatePresignedUrl(ctx echo.Context) error {
	var request CreatePresignedUrlRequestObject

	var body CreatePresignedUrlJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePresignedUrl(ctx.Request().Context(), request.(CreatePresignedUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePresignedUrl")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreatePresignedUrlResponseObject); ok {
		return validResponse.VisitCreatePresignedUrlResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostPublish operation middleware
func (sh *strictHandler) PostPublish(ctx echo.Context) error {
	var request PostPublishRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostPublish(ctx.Request().Context(), request.(PostPublishRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPublish")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostPublishResponseObject); ok {
		return validResponse.VisitPostPublishResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetQuestions operation middleware
func (sh *strictHandler) GetQuestions(ctx echo.Context, params GetQuestionsParams) error {
	var request GetQuestionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuestions(ctx.Request().Context(), request.(GetQuestionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuestions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetQuestionsResponseObject); ok {
		return validResponse.VisitGetQuestionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateQuestion operation middleware
func (sh *strictHandler) CreateQuestion(ctx echo.Context) error {
	var request CreateQuestionRequestObject

	var body CreateQuestionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateQuestion(ctx.Request().Context(), request.(CreateQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateQuestion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateQuestionResponseObject); ok {
		return validResponse.VisitCreateQuestionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteQuestion operation middleware
func (sh *strictHandler) DeleteQuestion(ctx echo.Context, questionId int64) error {
	var request DeleteQuestionRequestObject

	request.QuestionId = questionId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteQuestion(ctx.Request().Context(), request.(DeleteQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteQuestion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteQuestionResponseObject); ok {
		return validResponse.VisitDeleteQuestionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetQuestion operation middleware
func (sh *strictHandler) GetQuestion(ctx echo.Context, questionId int64) error {
	var request GetQuestionRequestObject

	request.QuestionId = questionId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuestion(ctx.Request().Context(), request.(GetQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuestion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetQuestionResponseObject); ok {
		return validResponse.VisitGetQuestionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateQuestion operation middleware
func (sh *strictHandler) UpdateQuestion(ctx echo.Context, questionId int64) error {
	var request UpdateQuestionRequestObject

	request.QuestionId = questionId

	var body UpdateQuestionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateQuestion(ctx.Request().Context(), request.(UpdateQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateQuestion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateQuestionResponseObject); ok {
		return validResponse.VisitUpdateQuestionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUsers operation middleware
func (sh *strictHandler) GetUsers(ctx echo.Context, params GetUsersParams) error {
	var request GetUsersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsers(ctx.Request().Context(), request.(GetUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUsersResponseObject); ok {
		return validResponse.VisitGetUsersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetWorkbooks operation middleware
func (sh *strictHandler) GetWorkbooks(ctx echo.Context, params GetWorkbooksParams) error {
	var request GetWorkbooksRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkbooks(ctx.Request().Context(), request.(GetWorkbooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkbooks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWorkbooksResponseObject); ok {
		return validResponse.VisitGetWorkbooksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateWorkbook operation middleware
func (sh *strictHandler) CreateWorkbook(ctx echo.Context) error {
	var request CreateWorkbookRequestObject

	var body CreateWorkbookJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWorkbook(ctx.Request().Context(), request.(CreateWorkbookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWorkbook")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateWorkbookResponseObject); ok {
		return validResponse.VisitCreateWorkbookResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteWorkbook operation middleware
func (sh *strictHandler) DeleteWorkbook(ctx echo.Context, workbookId int64) error {
	var request DeleteWorkbookRequestObject

	request.WorkbookId = workbookId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteWorkbook(ctx.Request().Context(), request.(DeleteWorkbookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteWorkbook")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteWorkbookResponseObject); ok {
		return validResponse.VisitDeleteWorkbookResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetWorkbook operation middleware
func (sh *strictHandler) GetWorkbook(ctx echo.Context, workbookId int64) error {
	var request GetWorkbookRequestObject

	request.WorkbookId = workbookId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkbook(ctx.Request().Context(), request.(GetWorkbookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkbook")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWorkbookResponseObject); ok {
		return validResponse.VisitGetWorkbookResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateWorkbook operation middleware
func (sh *strictHandler) UpdateWorkbook(ctx echo.Context, workbookId int64) error {
	var request UpdateWorkbookRequestObject

	request.WorkbookId = workbookId

	var body UpdateWorkbookJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateWorkbook(ctx.Request().Context(), request.(UpdateWorkbookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateWorkbook")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateWorkbookResponseObject); ok {
		return validResponse.VisitUpdateWorkbookResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
