// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// Defines values for QuestionType.
const (
	SingleChoice QuestionType = "single_choice"
)

// Valid indicates whether the value is a known member of the QuestionType enum.
func (e QuestionType) Valid() bool {
	switch e {
	case SingleChoice:
		return true
	default:
		return false
	}
}

// AnonymousSignInResponse defines model for AnonymousSignInResponse.
type AnonymousSignInResponse struct {
	// IdentityId Cognito Identity ID
	IdentityId string `json:"identityId"`
}

// AnswerItem defines model for AnswerItem.
type AnswerItem struct {
	QuestionId     int64 `json:"questionId"`
	SelectedChoice int   `json:"selectedChoice"`
}

// AnswerLogItem defines model for AnswerLogItem.
type AnswerLogItem struct {
	AnsweredAt     time.Time `json:"answeredAt"`
	Id             int64     `json:"id"`
	IsCorrect      bool      `json:"isCorrect"`
	QuestionId     int64     `json:"questionId"`
	QuestionText   string    `json:"questionText"`
	SelectedChoice int       `json:"selectedChoice"`
	WorkbookId     int64     `json:"workbookId"`
	WorkbookTitle  string    `json:"workbookTitle"`
}

// AnswerLogsResponse defines model for AnswerLogsResponse.
type AnswerLogsResponse struct {
	Logs  []AnswerLogItem `json:"logs"`
	Total int             `json:"total"`
}

// AppStatusResponse defines model for AppStatusResponse.
type AppStatusResponse struct {
	// IsMaintenance メンテナンス中かどうか
	IsMaintenance bool `json:"isMaintenance"`

	// LatestVersion 最新アプリバージョン
	LatestVersion string `json:"latestVersion"`

	// MaintenanceMessage メンテナンス中のメッセージ
	MaintenanceMessage string `json:"maintenanceMessage"`

	// MinimumVersion 最低限必要なアプリバージョン
	MinimumVersion string `json:"minimumVersion"`
}

// CategoriesResponse defines model for CategoriesResponse.
type CategoriesResponse struct {
	Categories []Category `json:"categories"`

	// Total 総件数
	Total int `json:"total"`
}

// Category defines model for Category.
type Category struct {
	Description *string `json:"description,omitempty"`
	Id          int64   `json:"id"`
	Title       string  `json:"title"`

	// WorkbookCount 問題集数
	WorkbookCount *int `json:"workbookCount,omitempty"`
}

// CategoryDetail defines model for CategoryDetail.
type CategoryDetail struct {
	Description *string    `json:"description,omitempty"`
	Id          int64      `json:"id"`
	Title       string     `json:"title"`
	Workbooks   []Workbook `json:"workbooks"`
}

// Error defines model for Error.
type Error struct {
	// Code 機械可読なエラーコード
	Code string `json:"code"`

	// Message 人間可読なエラーメッセージ
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// Question defines model for Question.
type Question struct {
	Choices []string `json:"choices"`

	// Correct 正解の選択肢インデックス
	Correct *int `json:"correct,omitempty"`

	// Explanation 解説
	Explanation *string `json:"explanation,omitempty"`
	Id          int64   `json:"id"`

	// Images 画像URL
	Images *[]string    `json:"images,omitempty"`
	Text   string       `json:"text"`
	Type   QuestionType `json:"type"`
}

// QuestionType defines model for Question.Type.
type QuestionType string

// QuestionsResponse defines model for QuestionsResponse.
type QuestionsResponse struct {
	Questions []Question `json:"questions"`

	// Total 総件数
	Total int `json:"total"`
}

// SubmitAnswersRequest defines model for SubmitAnswersRequest.
type SubmitAnswersRequest struct {
	Answers    []AnswerItem `json:"answers"`
	WorkbookId int64        `json:"workbookId"`
}

// SubmitAnswersResponse defines model for SubmitAnswersResponse.
type SubmitAnswersResponse struct {
	CorrectCount int `json:"correctCount"`
	TotalCount   int `json:"totalCount"`
}

// UpdateUserProfileRequest defines model for UpdateUserProfileRequest.
type UpdateUserProfileRequest struct {
	DisplayName        *string `json:"displayName,omitempty"`
	SelectedWorkbookId *int64  `json:"selectedWorkbookId,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	DisplayName        *string `json:"displayName,omitempty"`
	IdentityId         string  `json:"identityId"`
	SelectedWorkbookId *int64  `json:"selectedWorkbookId,omitempty"`
	UserId             *int64  `json:"userId,omitempty"`
}

// Workbook defines model for Workbook.
type Workbook struct {
	// CategoryId カテゴリID
	CategoryId  *int64  `json:"categoryId,omitempty"`
	Description *string `json:"description,omitempty"`
	Id          int64   `json:"id"`

	// QuestionCount 問題数
	QuestionCount *int   `json:"questionCount,omitempty"`
	Title         string `json:"title"`
}

// WorkbookDetail defines model for WorkbookDetail.
type WorkbookDetail struct {
	// CategoryId カテゴリID
	CategoryId  *int64     `json:"categoryId,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          int64      `json:"id"`
	Questions   []Question `json:"questions"`
	Title       string     `json:"title"`
}

// WorkbooksResponse defines model for WorkbooksResponse.
type WorkbooksResponse struct {
	// Total 総件数
	Total     int        `json:"total"`
	Workbooks []Workbook `json:"workbooks"`
}

// WrongAnswersResponse defines model for WrongAnswersResponse.
type WrongAnswersResponse struct {
	Questions []Question `json:"questions"`
	Total     int        `json:"total"`
}

// DeviceID defines model for DeviceID.
type DeviceID = string

// SubmitAnswersParams defines parameters for SubmitAnswers.
type SubmitAnswersParams struct {
	// XDeviceID Cognito Identity ID（匿名ユーザー識別子）
	XDeviceID DeviceID `json:"X-Device-ID"`
}

// AnonymousSignOutParams defines parameters for AnonymousSignOut.
type AnonymousSignOutParams struct {
	// XDeviceID Cognito Identity ID（匿名ユーザー識別子）
	XDeviceID DeviceID `json:"X-Device-ID"`
}

// GetCategoriesParams defines parameters for GetCategories.
type GetCategoriesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetQuestionsParams defines parameters for GetQuestions.
type GetQuestionsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetUserProfileParams defines parameters for GetUserProfile.
type GetUserProfileParams struct {
	// XDeviceID Cognito Identity ID（匿名ユーザー識別子）
	XDeviceID DeviceID `json:"X-Device-ID"`
	XAppSlug  string   `json:"X-App-Slug"`
}

// UpdateUserProfileParams defines parameters for UpdateUserProfile.
type UpdateUserProfileParams struct {
	// XDeviceID Cognito Identity ID（匿名ユーザー識別子）
	XDeviceID DeviceID `json:"X-Device-ID"`
	XAppSlug  string   `json:"X-App-Slug"`
}

// GetAnswerLogsParams defines parameters for GetAnswerLogs.
type GetAnswerLogsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// XDeviceID Cognito Identity ID（匿名ユーザー識別子）
	XDeviceID DeviceID `json:"X-Device-ID"`
}

// GetWrongAnswersParams defines parameters for GetWrongAnswers.
type GetWrongAnswersParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// XDeviceID Cognito Identity ID（匿名ユーザー識別子）
	XDeviceID DeviceID `json:"X-Device-ID"`
}

// GetWorkbooksParams defines parameters for GetWorkbooks.
type GetWorkbooksParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SubmitAnswersJSONRequestBody defines body for SubmitAnswers for application/json ContentType.
type SubmitAnswersJSONRequestBody = SubmitAnswersRequest

// UpdateUserProfileJSONRequestBody defines body for UpdateUserProfile for application/json ContentType.
type UpdateUserProfileJSONRequestBody = UpdateUserProfileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ルート
	// (GET /)
	Root(ctx echo.Context) error
	// 回答送信
	// (POST /answers)
	SubmitAnswers(ctx echo.Context, params SubmitAnswersParams) error
	// 匿名サインイン
	// (POST /auth/anonymous/sign-in)
	AnonymousSignIn(ctx echo.Context) error
	// 匿名サインアウト
	// (POST /auth/anonymous/sign-out)
	AnonymousSignOut(ctx echo.Context, params AnonymousSignOutParams) error
	// カテゴリ一覧取得
	// (GET /categories)
	GetCategories(ctx echo.Context, params GetCategoriesParams) error
	// カテゴリ詳細取得
	// (GET /categories/{categoryId})
	GetCategory(ctx echo.Context, categoryId int64) error
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// 問題一覧取得
	// (GET /questions)
	GetQuestions(ctx echo.Context, params GetQuestionsParams) error
	// 問題詳細取得
	// (GET /questions/{questionId})
	GetQuestion(ctx echo.Context, questionId int64) error
	// アプリステータス取得
	// (GET /status)
	GetAppStatus(ctx echo.Context) error
	// ユーザープロフィール取得
	// (GET /users/me)
	GetUserProfile(ctx echo.Context, params GetUserProfileParams) error
	// ユーザープロフィール更新
	// (PUT /users/me)
	UpdateUserProfile(ctx echo.Context, params UpdateUserProfileParams) error
	// 解答ログ一覧
	// (GET /users/me/answer-logs)
	GetAnswerLogs(ctx echo.Context, params GetAnswerLogsParams) error
	// 間違えた問題一覧
	// (GET /users/me/wrong-answers)
	GetWrongAnswers(ctx echo.Context, params GetWrongAnswersParams) error
	// 問題集一覧取得
	// (GET /workbooks)
	GetWorkbooks(ctx echo.Context, params GetWorkbooksParams) error
	// 問題集詳細取得
	// (GET /workbooks/{workbookId})
	GetWorkbook(ctx echo.Context, workbookId int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Root converts echo context to params.
func (w *ServerInterfaceWrapper) Root(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Root(ctx)
	return err
}

// SubmitAnswers converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitAnswers(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SubmitAnswersParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-ID")]; found {
		var XDeviceID DeviceID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-ID", valueList[0], &XDeviceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-ID: %s", err))
		}

		params.XDeviceID = XDeviceID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitAnswers(ctx, params)
	return err
}

// AnonymousSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) AnonymousSignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AnonymousSignIn(ctx)
	return err
}

// AnonymousSignOut converts echo context to params.
func (w *ServerInterfaceWrapper) AnonymousSignOut(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AnonymousSignOutParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-ID")]; found {
		var XDeviceID DeviceID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-ID", valueList[0], &XDeviceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-ID: %s", err))
		}

		params.XDeviceID = XDeviceID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AnonymousSignOut(ctx, params)
	return err
}

// GetCategories converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategories(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCategoriesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategories(ctx, params)
	return err
}

// GetCategory converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "categoryId" -------------
	var categoryId int64

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", ctx.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategory(ctx, categoryId)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// GetQuestions converts echo context to params.
func (w *ServerInterfaceWrapper) GetQuestions(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetQuestionsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetQuestions(ctx, params)
	return err
}

// GetQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) GetQuestion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "questionId" -------------
	var questionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", ctx.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter questionId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetQuestion(ctx, questionId)
	return err
}

// GetAppStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetAppStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAppStatus(ctx)
	return err
}

// GetUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserProfile(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserProfileParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-ID")]; found {
		var XDeviceID DeviceID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-ID", valueList[0], &XDeviceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-ID: %s", err))
		}

		params.XDeviceID = XDeviceID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-ID is required, but not found"))
	}
	// ------------- Required header parameter "X-App-Slug" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-App-Slug")]; found {
		var XAppSlug string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-App-Slug, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-App-Slug", valueList[0], &XAppSlug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-App-Slug: %s", err))
		}

		params.XAppSlug = XAppSlug
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-App-Slug is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserProfile(ctx, params)
	return err
}

// UpdateUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserProfile(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateUserProfileParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-ID")]; found {
		var XDeviceID DeviceID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-ID", valueList[0], &XDeviceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-ID: %s", err))
		}

		params.XDeviceID = XDeviceID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-ID is required, but not found"))
	}
	// ------------- Required header parameter "X-App-Slug" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-App-Slug")]; found {
		var XAppSlug string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-App-Slug, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-App-Slug", valueList[0], &XAppSlug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-App-Slug: %s", err))
		}

		params.XAppSlug = XAppSlug
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-App-Slug is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserProfile(ctx, params)
	return err
}

// GetAnswerLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetAnswerLogs(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAnswerLogsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-ID")]; found {
		var XDeviceID DeviceID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-ID", valueList[0], &XDeviceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-ID: %s", err))
		}

		params.XDeviceID = XDeviceID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAnswerLogs(ctx, params)
	return err
}

// GetWrongAnswers converts echo context to params.
func (w *ServerInterfaceWrapper) GetWrongAnswers(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWrongAnswersParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-ID")]; found {
		var XDeviceID DeviceID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-ID", valueList[0], &XDeviceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-ID: %s", err))
		}

		params.XDeviceID = XDeviceID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWrongAnswers(ctx, params)
	return err
}

// GetWorkbooks converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkbooks(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkbooksParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkbooks(ctx, params)
	return err
}

// GetWorkbook converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkbook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "workbookId" -------------
	var workbookId int64

	err = runtime.BindStyledParameterWithOptions("simple", "workbookId", ctx.Param("workbookId"), &workbookId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter workbookId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkbook(ctx, workbookId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/", wrapper.Root)
	router.POST(baseURL+"/answers", wrapper.SubmitAnswers)
	router.POST(baseURL+"/auth/anonymous/sign-in", wrapper.AnonymousSignIn)
	router.POST(baseURL+"/auth/anonymous/sign-out", wrapper.AnonymousSignOut)
	router.GET(baseURL+"/categories", wrapper.GetCategories)
	router.GET(baseURL+"/categories/:categoryId", wrapper.GetCategory)
	router.GET(baseURL+"/health", wrapper.HealthCheck)
	router.GET(baseURL+"/questions", wrapper.GetQuestions)
	router.GET(baseURL+"/questions/:questionId", wrapper.GetQuestion)
	router.GET(baseURL+"/status", wrapper.GetAppStatus)
	router.GET(baseURL+"/users/me", wrapper.GetUserProfile)
	router.PUT(baseURL+"/users/me", wrapper.UpdateUserProfile)
	router.GET(baseURL+"/users/me/answer-logs", wrapper.GetAnswerLogs)
	router.GET(baseURL+"/users/me/wrong-answers", wrapper.GetWrongAnswers)
	router.GET(baseURL+"/workbooks", wrapper.GetWorkbooks)
	router.GET(baseURL+"/workbooks/:workbookId", wrapper.GetWorkbook)

}

type RootRequestObject struct {
}

type RootResponseObject interface {
	VisitRootResponse(w http.ResponseWriter) error
}

type Root200JSONResponse MessageResponse

func (response Root200JSONResponse) VisitRootResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SubmitAnswersRequestObject struct {
	Params SubmitAnswersParams
	Body   *SubmitAnswersJSONRequestBody
}

type SubmitAnswersResponseObject interface {
	VisitSubmitAnswersResponse(w http.ResponseWriter) error
}

type SubmitAnswers200JSONResponse SubmitAnswersResponse

func (response SubmitAnswers200JSONResponse) VisitSubmitAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SubmitAnswers400JSONResponse Error

func (response SubmitAnswers400JSONResponse) VisitSubmitAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AnonymousSignInRequestObject struct {
}

type AnonymousSignInResponseObject interface {
	VisitAnonymousSignInResponse(w http.ResponseWriter) error
}

type AnonymousSignIn200JSONResponse AnonymousSignInResponse

func (response AnonymousSignIn200JSONResponse) VisitAnonymousSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AnonymousSignIn500JSONResponse Error

func (response AnonymousSignIn500JSONResponse) VisitAnonymousSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AnonymousSignOutRequestObject struct {
	Params AnonymousSignOutParams
}

type AnonymousSignOutResponseObject interface {
	VisitAnonymousSignOutResponse(w http.ResponseWriter) error
}

type AnonymousSignOut204Response struct {
}

func (response AnonymousSignOut204Response) VisitAnonymousSignOutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AnonymousSignOut400JSONResponse Error

func (response AnonymousSignOut400JSONResponse) VisitAnonymousSignOutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesRequestObject struct {
	Params GetCategoriesParams
}

type GetCategoriesResponseObject interface {
	VisitGetCategoriesResponse(w http.ResponseWriter) error
}

type GetCategories200JSONResponse CategoriesResponse

func (response GetCategories200JSONResponse) VisitGetCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCategories400JSONResponse Error

func (response GetCategories400JSONResponse) VisitGetCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoryRequestObject struct {
	CategoryId int64 `json:"categoryId"`
}

type GetCategoryResponseObject interface {
	VisitGetCategoryResponse(w http.ResponseWriter) error
}

type GetCategory200JSONResponse CategoryDetail

func (response GetCategory200JSONResponse) VisitGetCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCategory404JSONResponse Error

func (response GetCategory404JSONResponse) VisitGetCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthResponse

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestionsRequestObject struct {
	Params GetQuestionsParams
}

type GetQuestionsResponseObject interface {
	VisitGetQuestionsResponse(w http.ResponseWriter) error
}

type GetQuestions200JSONResponse QuestionsResponse

func (response GetQuestions200JSONResponse) VisitGetQuestionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestions400JSONResponse Error

func (response GetQuestions400JSONResponse) VisitGetQuestionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestionRequestObject struct {
	QuestionId int64 `json:"questionId"`
}

type GetQuestionResponseObject interface {
	VisitGetQuestionResponse(w http.ResponseWriter) error
}

type GetQuestion200JSONResponse Question

func (response GetQuestion200JSONResponse) VisitGetQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestion404JSONResponse Error

func (response GetQuestion404JSONResponse) VisitGetQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAppStatusRequestObject struct {
}

type GetAppStatusResponseObject interface {
	VisitGetAppStatusResponse(w http.ResponseWriter) error
}

type GetAppStatus200JSONResponse AppStatusResponse

func (response GetAppStatus200JSONResponse) VisitGetAppStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfileRequestObject struct {
	Params GetUserProfileParams
}

type GetUserProfileResponseObject interface {
	VisitGetUserProfileResponse(w http.ResponseWriter) error
}

type GetUserProfile200JSONResponse UserProfile

func (response GetUserProfile200JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfile400JSONResponse Error

func (response GetUserProfile400JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserProfileRequestObject struct {
	Params UpdateUserProfileParams
	Body   *UpdateUserProfileJSONRequestBody
}

type UpdateUserProfileResponseObject interface {
	VisitUpdateUserProfileResponse(w http.ResponseWriter) error
}

type UpdateUserProfile200JSONResponse UserProfile

func (response UpdateUserProfile200JSONResponse) VisitUpdateUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserProfile400JSONResponse Error

func (response UpdateUserProfile400JSONResponse) VisitUpdateUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswerLogsRequestObject struct {
	Params GetAnswerLogsParams
}

type GetAnswerLogsResponseObject interface {
	VisitGetAnswerLogsResponse(w http.ResponseWriter) error
}

type GetAnswerLogs200JSONResponse AnswerLogsResponse

func (response GetAnswerLogs200JSONResponse) VisitGetAnswerLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswerLogs400JSONResponse Error

func (response GetAnswerLogs400JSONResponse) VisitGetAnswerLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetWrongAnswersRequestObject struct {
	Params GetWrongAnswersParams
}

type GetWrongAnswersResponseObject interface {
	VisitGetWrongAnswersResponse(w http.ResponseWriter) error
}

type GetWrongAnswers200JSONResponse WrongAnswersResponse

func (response GetWrongAnswers200JSONResponse) VisitGetWrongAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWrongAnswers400JSONResponse Error

func (response GetWrongAnswers400JSONResponse) VisitGetWrongAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbooksRequestObject struct {
	Params GetWorkbooksParams
}

type GetWorkbooksResponseObject interface {
	VisitGetWorkbooksResponse(w http.ResponseWriter) error
}

type GetWorkbooks200JSONResponse WorkbooksResponse

func (response GetWorkbooks200JSONResponse) VisitGetWorkbooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbooks400JSONResponse Error

func (response GetWorkbooks400JSONResponse) VisitGetWorkbooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbookRequestObject struct {
	WorkbookId int64 `json:"workbookId"`
}

type GetWorkbookResponseObject interface {
	VisitGetWorkbookResponse(w http.ResponseWriter) error
}

type GetWorkbook200JSONResponse WorkbookDetail

func (response GetWorkbook200JSONResponse) VisitGetWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbook404JSONResponse Error

func (response GetWorkbook404JSONResponse) VisitGetWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ルート
	// (GET /)
	Root(ctx context.Context, request RootRequestObject) (RootResponseObject, error)
	// 回答送信
	// (POST /answers)
	SubmitAnswers(ctx context.Context, request SubmitAnswersRequestObject) (SubmitAnswersResponseObject, error)
	// 匿名サインイン
	// (POST /auth/anonymous/sign-in)
	AnonymousSignIn(ctx context.Context, request AnonymousSignInRequestObject) (AnonymousSignInResponseObject, error)
	// 匿名サインアウト
	// (POST /auth/anonymous/sign-out)
	AnonymousSignOut(ctx context.Context, request AnonymousSignOutRequestObject) (AnonymousSignOutResponseObject, error)
	// カテゴリ一覧取得
	// (GET /categories)
	GetCategories(ctx context.Context, request GetCategoriesRequestObject) (GetCategoriesResponseObject, error)
	// カテゴリ詳細取得
	// (GET /categories/{categoryId})
	GetCategory(ctx context.Context, request GetCategoryRequestObject) (GetCategoryResponseObject, error)
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// 問題一覧取得
	// (GET /questions)
	GetQuestions(ctx context.Context, request GetQuestionsRequestObject) (GetQuestionsResponseObject, error)
	// 問題詳細取得
	// (GET /questions/{questionId})
	GetQuestion(ctx context.Context, request GetQuestionRequestObject) (GetQuestionResponseObject, error)
	// アプリステータス取得
	// (GET /status)
	GetAppStatus(ctx context.Context, request GetAppStatusRequestObject) (GetAppStatusResponseObject, error)
	// ユーザープロフィール取得
	// (GET /users/me)
	GetUserProfile(ctx context.Context, request GetUserProfileRequestObject) (GetUserProfileResponseObject, error)
	// ユーザープロフィール更新
	// (PUT /users/me)
	UpdateUserProfile(ctx context.Context, request UpdateUserProfileRequestObject) (UpdateUserProfileResponseObject, error)
	// 解答ログ一覧
	// (GET /users/me/answer-logs)
	GetAnswerLogs(ctx context.Context, request GetAnswerLogsRequestObject) (GetAnswerLogsResponseObject, error)
	// 間違えた問題一覧
	// (GET /users/me/wrong-answers)
	GetWrongAnswers(ctx context.Context, request GetWrongAnswersRequestObject) (GetWrongAnswersResponseObject, error)
	// 問題集一覧取得
	// (GET /workbooks)
	GetWorkbooks(ctx context.Context, request GetWorkbooksRequestObject) (GetWorkbooksResponseObject, error)
	// 問題集詳細取得
	// (GET /workbooks/{workbookId})
	GetWorkbook(ctx context.Context, request GetWorkbookRequestObject) (GetWorkbookResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Root operation middleware
func (sh *strictHandler) Root(ctx echo.Context) error {
	var request RootRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Root(ctx.Request().Context(), request.(RootRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Root")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RootResponseObject); ok {
		return validResponse.VisitRootResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SubmitAnswers operation middleware
func (sh *strictHandler) SubmitAnswers(ctx echo.Context, params SubmitAnswersParams) error {
	var request SubmitAnswersRequestObject

	request.Params = params

	var body SubmitAnswersJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitAnswers(ctx.Request().Context(), request.(SubmitAnswersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitAnswers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SubmitAnswersResponseObject); ok {
		return validResponse.VisitSubmitAnswersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AnonymousSignIn operation middleware
func (sh *strictHandler) AnonymousSignIn(ctx echo.Context) error {
	var request AnonymousSignInRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AnonymousSignIn(ctx.Request().Context(), request.(AnonymousSignInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AnonymousSignIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AnonymousSignInResponseObject); ok {
		return validResponse.VisitAnonymousSignInResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AnonymousSignOut operation middleware
func (sh *strictHandler) AnonymousSignOut(ctx echo.Context, params AnonymousSignOutParams) error {
	var request AnonymousSignOutRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AnonymousSignOut(ctx.Request().Context(), request.(AnonymousSignOutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AnonymousSignOut")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AnonymousSignOutResponseObject); ok {
		return validResponse.VisitAnonymousSignOutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCategories operation middleware
func (sh *strictHandler) GetCategories(ctx echo.Context, params GetCategoriesParams) error {
	var request GetCategoriesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategories(ctx.Request().Context(), request.(GetCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCategoriesResponseObject); ok {
		return validResponse.VisitGetCategoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCategory operation middleware
func (sh *strictHandler) GetCategory(ctx echo.Context, categoryId int64) error {
	var request GetCategoryRequestObject

	request.CategoryId = categoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategory(ctx.Request().Context(), request.(GetCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCategoryResponseObject); ok {
		return validResponse.VisitGetCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(ctx echo.Context) error {
	var request HealthCheckRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx.Request().Context(), request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		return validResponse.VisitHealthCheckResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetQuestions operation middleware
func (sh *strictHandler) GetQuestions(ctx echo.Context, params GetQuestionsParams) error {
	var request GetQuestionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuestions(ctx.Request().Context(), request.(GetQuestionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuestions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetQuestionsResponseObject); ok {
		return validResponse.VisitGetQuestionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetQuestion operation middleware
func (sh *strictHandler) GetQuestion(ctx echo.Context, questionId int64) error {
	var request GetQuestionRequestObject

	request.QuestionId = questionId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuestion(ctx.Request().Context(), request.(GetQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuestion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetQuestionResponseObject); ok {
		return validResponse.VisitGetQuestionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAppStatus operation middleware
func (sh *strictHandler) GetAppStatus(ctx echo.Context) error {
	var request GetAppStatusRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAppStatus(ctx.Request().Context(), request.(GetAppStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAppStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAppStatusResponseObject); ok {
		return validResponse.VisitGetAppStatusResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserProfile operation middleware
func (sh *strictHandler) GetUserProfile(ctx echo.Context, params GetUserProfileParams) error {
	var request GetUserProfileRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserProfile(ctx.Request().Context(), request.(GetUserProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserProfileResponseObject); ok {
		return validResponse.VisitGetUserProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUserProfile operation middleware
func (sh *strictHandler) UpdateUserProfile(ctx echo.Context, params UpdateUserProfileParams) error {
	var request UpdateUserProfileRequestObject

	request.Params = params

	var body UpdateUserProfileJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserProfile(ctx.Request().Context(), request.(UpdateUserProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserProfileResponseObject); ok {
		return validResponse.VisitUpdateUserProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAnswerLogs operation middleware
func (sh *strictHandler) GetAnswerLogs(ctx echo.Context, params GetAnswerLogsParams) error {
	var request GetAnswerLogsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAnswerLogs(ctx.Request().Context(), request.(GetAnswerLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAnswerLogs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAnswerLogsResponseObject); ok {
		return validResponse.VisitGetAnswerLogsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetWrongAnswers operation middleware
func (sh *strictHandler) GetWrongAnswers(ctx echo.Context, params GetWrongAnswersParams) error {
	var request GetWrongAnswersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWrongAnswers(ctx.Request().Context(), request.(GetWrongAnswersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWrongAnswers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWrongAnswersResponseObject); ok {
		return validResponse.VisitGetWrongAnswersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetWorkbooks operation middleware
func (sh *strictHandler) GetWorkbooks(ctx echo.Context, params GetWorkbooksParams) error {
	var request GetWorkbooksRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkbooks(ctx.Request().Context(), request.(GetWorkbooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkbooks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWorkbooksResponseObject); ok {
		return validResponse.VisitGetWorkbooksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetWorkbook operation middleware
func (sh *strictHandler) GetWorkbook(ctx echo.Context, workbookId int64) error {
	var request GetWorkbookRequestObject

	request.WorkbookId = workbookId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkbook(ctx.Request().Context(), request.(GetWorkbookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkbook")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWorkbookResponseObject); ok {
		return validResponse.VisitGetWorkbookResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
