// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for QuestionType.
const (
	SingleChoice QuestionType = "single_choice"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// Question defines model for Question.
type Question struct {
	Choices []string `json:"choices"`

	// Correct 正解の選択肢インデックス
	Correct *int `json:"correct,omitempty"`

	// Explanation 解説
	Explanation *string            `json:"explanation,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// Images 紐付く画像ID
	Images *[]openapi_types.UUID `json:"images,omitempty"`
	Text   string                `json:"text"`
	Type   QuestionType          `json:"type"`
}

// QuestionType defines model for Question.Type.
type QuestionType string

// QuestionsResponse defines model for QuestionsResponse.
type QuestionsResponse struct {
	Questions []Question `json:"questions"`

	// Total 総件数
	Total int `json:"total"`
}

// Workbook defines model for Workbook.
type Workbook struct {
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// QuestionCount 問題数
	QuestionCount *int   `json:"questionCount,omitempty"`
	Title         string `json:"title"`
}

// WorkbookDetail defines model for WorkbookDetail.
type WorkbookDetail struct {
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Questions   []Question         `json:"questions"`
	Title       string             `json:"title"`
}

// WorkbooksResponse defines model for WorkbooksResponse.
type WorkbooksResponse struct {
	// Total 総件数
	Total     int        `json:"total"`
	Workbooks []Workbook `json:"workbooks"`
}

// GetQuestionsParams defines parameters for GetQuestions.
type GetQuestionsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetWorkbooksParams defines parameters for GetWorkbooks.
type GetWorkbooksParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ルート
	// (GET /)
	Root(ctx echo.Context) error
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// 画像取得
	// (GET /images/{imageId})
	GetImage(ctx echo.Context, imageId openapi_types.UUID) error
	// 問題一覧取得
	// (GET /questions)
	GetQuestions(ctx echo.Context, params GetQuestionsParams) error
	// 問題詳細取得
	// (GET /questions/{questionId})
	GetQuestion(ctx echo.Context, questionId openapi_types.UUID) error
	// 問題集一覧取得
	// (GET /workbooks)
	GetWorkbooks(ctx echo.Context, params GetWorkbooksParams) error
	// 問題集詳細取得
	// (GET /workbooks/{workbookId})
	GetWorkbook(ctx echo.Context, workbookId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Root converts echo context to params.
func (w *ServerInterfaceWrapper) Root(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Root(ctx)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// GetImage converts echo context to params.
func (w *ServerInterfaceWrapper) GetImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "imageId" -------------
	var imageId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "imageId", ctx.Param("imageId"), &imageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter imageId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetImage(ctx, imageId)
	return err
}

// GetQuestions converts echo context to params.
func (w *ServerInterfaceWrapper) GetQuestions(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetQuestionsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetQuestions(ctx, params)
	return err
}

// GetQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) GetQuestion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "questionId" -------------
	var questionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", ctx.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter questionId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetQuestion(ctx, questionId)
	return err
}

// GetWorkbooks converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkbooks(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkbooksParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkbooks(ctx, params)
	return err
}

// GetWorkbook converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkbook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "workbookId" -------------
	var workbookId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workbookId", ctx.Param("workbookId"), &workbookId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter workbookId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkbook(ctx, workbookId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/", wrapper.Root)
	router.GET(baseURL+"/health", wrapper.HealthCheck)
	router.GET(baseURL+"/images/:imageId", wrapper.GetImage)
	router.GET(baseURL+"/questions", wrapper.GetQuestions)
	router.GET(baseURL+"/questions/:questionId", wrapper.GetQuestion)
	router.GET(baseURL+"/workbooks", wrapper.GetWorkbooks)
	router.GET(baseURL+"/workbooks/:workbookId", wrapper.GetWorkbook)

}

type RootRequestObject struct {
}

type RootResponseObject interface {
	VisitRootResponse(w http.ResponseWriter) error
}

type Root200JSONResponse MessageResponse

func (response Root200JSONResponse) VisitRootResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthResponse

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetImageRequestObject struct {
	ImageId openapi_types.UUID `json:"imageId"`
}

type GetImageResponseObject interface {
	VisitGetImageResponse(w http.ResponseWriter) error
}

type GetImage200ImagepngResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetImage200ImagepngResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetImage404JSONResponse Error

func (response GetImage404JSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestionsRequestObject struct {
	Params GetQuestionsParams
}

type GetQuestionsResponseObject interface {
	VisitGetQuestionsResponse(w http.ResponseWriter) error
}

type GetQuestions200JSONResponse QuestionsResponse

func (response GetQuestions200JSONResponse) VisitGetQuestionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestionRequestObject struct {
	QuestionId openapi_types.UUID `json:"questionId"`
}

type GetQuestionResponseObject interface {
	VisitGetQuestionResponse(w http.ResponseWriter) error
}

type GetQuestion200JSONResponse Question

func (response GetQuestion200JSONResponse) VisitGetQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestion404JSONResponse Error

func (response GetQuestion404JSONResponse) VisitGetQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbooksRequestObject struct {
	Params GetWorkbooksParams
}

type GetWorkbooksResponseObject interface {
	VisitGetWorkbooksResponse(w http.ResponseWriter) error
}

type GetWorkbooks200JSONResponse WorkbooksResponse

func (response GetWorkbooks200JSONResponse) VisitGetWorkbooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbookRequestObject struct {
	WorkbookId openapi_types.UUID `json:"workbookId"`
}

type GetWorkbookResponseObject interface {
	VisitGetWorkbookResponse(w http.ResponseWriter) error
}

type GetWorkbook200JSONResponse WorkbookDetail

func (response GetWorkbook200JSONResponse) VisitGetWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkbook404JSONResponse Error

func (response GetWorkbook404JSONResponse) VisitGetWorkbookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ルート
	// (GET /)
	Root(ctx context.Context, request RootRequestObject) (RootResponseObject, error)
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// 画像取得
	// (GET /images/{imageId})
	GetImage(ctx context.Context, request GetImageRequestObject) (GetImageResponseObject, error)
	// 問題一覧取得
	// (GET /questions)
	GetQuestions(ctx context.Context, request GetQuestionsRequestObject) (GetQuestionsResponseObject, error)
	// 問題詳細取得
	// (GET /questions/{questionId})
	GetQuestion(ctx context.Context, request GetQuestionRequestObject) (GetQuestionResponseObject, error)
	// 問題集一覧取得
	// (GET /workbooks)
	GetWorkbooks(ctx context.Context, request GetWorkbooksRequestObject) (GetWorkbooksResponseObject, error)
	// 問題集詳細取得
	// (GET /workbooks/{workbookId})
	GetWorkbook(ctx context.Context, request GetWorkbookRequestObject) (GetWorkbookResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Root operation middleware
func (sh *strictHandler) Root(ctx echo.Context) error {
	var request RootRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Root(ctx.Request().Context(), request.(RootRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Root")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RootResponseObject); ok {
		return validResponse.VisitRootResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(ctx echo.Context) error {
	var request HealthCheckRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx.Request().Context(), request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		return validResponse.VisitHealthCheckResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetImage operation middleware
func (sh *strictHandler) GetImage(ctx echo.Context, imageId openapi_types.UUID) error {
	var request GetImageRequestObject

	request.ImageId = imageId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetImage(ctx.Request().Context(), request.(GetImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetImageResponseObject); ok {
		return validResponse.VisitGetImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetQuestions operation middleware
func (sh *strictHandler) GetQuestions(ctx echo.Context, params GetQuestionsParams) error {
	var request GetQuestionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuestions(ctx.Request().Context(), request.(GetQuestionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuestions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetQuestionsResponseObject); ok {
		return validResponse.VisitGetQuestionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetQuestion operation middleware
func (sh *strictHandler) GetQuestion(ctx echo.Context, questionId openapi_types.UUID) error {
	var request GetQuestionRequestObject

	request.QuestionId = questionId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuestion(ctx.Request().Context(), request.(GetQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuestion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetQuestionResponseObject); ok {
		return validResponse.VisitGetQuestionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetWorkbooks operation middleware
func (sh *strictHandler) GetWorkbooks(ctx echo.Context, params GetWorkbooksParams) error {
	var request GetWorkbooksRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkbooks(ctx.Request().Context(), request.(GetWorkbooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkbooks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWorkbooksResponseObject); ok {
		return validResponse.VisitGetWorkbooksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetWorkbook operation middleware
func (sh *strictHandler) GetWorkbook(ctx echo.Context, workbookId openapi_types.UUID) error {
	var request GetWorkbookRequestObject

	request.WorkbookId = workbookId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkbook(ctx.Request().Context(), request.(GetWorkbookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkbook")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWorkbookResponseObject); ok {
		return validResponse.VisitGetWorkbookResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
