// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createAccountIfNotExists = `-- name: CreateAccountIfNotExists :one
INSERT INTO accounts (cognito_sub, email, primary_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (cognito_sub) DO NOTHING
RETURNING id, cognito_sub, email, primary_user_id
`

type CreateAccountIfNotExistsParams struct {
	CognitoSub    string         `json:"cognito_sub"`
	Email         sql.NullString `json:"email"`
	PrimaryUserID int64          `json:"primary_user_id"`
}

type CreateAccountIfNotExistsRow struct {
	ID            int64          `json:"id"`
	CognitoSub    string         `json:"cognito_sub"`
	Email         sql.NullString `json:"email"`
	PrimaryUserID int64          `json:"primary_user_id"`
}

// 同一 sub の並行初回リンクに耐えるため ON CONFLICT DO NOTHING。
// 競合した側は行が返らない（sql.ErrNoRows）ので、呼び出し側が再取得してマージ経路へ進む。
func (q *Queries) CreateAccountIfNotExists(ctx context.Context, arg CreateAccountIfNotExistsParams) (CreateAccountIfNotExistsRow, error) {
	row := q.db.QueryRowContext(ctx, createAccountIfNotExists, arg.CognitoSub, arg.Email, arg.PrimaryUserID)
	var i CreateAccountIfNotExistsRow
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.PrimaryUserID,
	)
	return i, err
}

const deleteAccountByID = `-- name: DeleteAccountByID :exec
DELETE FROM accounts WHERE id = $1
`

// accounts.primary_user_id は ON DELETE RESTRICT なので、users を消す前に account を消す
// （users.account_id は ON DELETE SET NULL）。
func (q *Queries) DeleteAccountByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccountByID, id)
	return err
}

const deleteUserAppSettingsByUser = `-- name: DeleteUserAppSettingsByUser :exec
DELETE FROM user_app_settings WHERE user_id = $1
`

func (q *Queries) DeleteUserAppSettingsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserAppSettingsByUser, userID)
	return err
}

const deleteUsersByIDs = `-- name: DeleteUsersByIDs :exec
DELETE FROM users WHERE id = ANY($1::bigint[])
`

// user_answers / user_app_settings は ON DELETE CASCADE で一緒に消える。
func (q *Queries) DeleteUsersByIDs(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.ExecContext(ctx, deleteUsersByIDs, pq.Array(dollar_1))
	return err
}

const getAccountByCognitoSub = `-- name: GetAccountByCognitoSub :one
SELECT id, cognito_sub, email, primary_user_id FROM accounts WHERE cognito_sub = $1
`

type GetAccountByCognitoSubRow struct {
	ID            int64          `json:"id"`
	CognitoSub    string         `json:"cognito_sub"`
	Email         sql.NullString `json:"email"`
	PrimaryUserID int64          `json:"primary_user_id"`
}

func (q *Queries) GetAccountByCognitoSub(ctx context.Context, cognitoSub string) (GetAccountByCognitoSubRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByCognitoSub, cognitoSub)
	var i GetAccountByCognitoSubRow
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.PrimaryUserID,
	)
	return i, err
}

const getPrimaryUserIDByIdentityID = `-- name: GetPrimaryUserIDByIdentityID :one
SELECT a.primary_user_id
FROM users u
JOIN accounts a ON a.id = u.account_id
WHERE u.identity_id = $1
`

// 端末が既にアカウントへ紐付いている場合の canonical user を引く。
// リンク済み端末はログアウト中でも同じアカウントへ読み書きさせるために使う
// （device user 側に回答が溜まると、再ログイン時の link は冪等 no-op なので回収されない）。
func (q *Queries) GetPrimaryUserIDByIdentityID(ctx context.Context, identityID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryUserIDByIdentityID, identityID)
	var primary_user_id int64
	err := row.Scan(&primary_user_id)
	return primary_user_id, err
}

const getUserAccountIDForUpdate = `-- name: GetUserAccountIDForUpdate :one
SELECT account_id FROM users WHERE id = $1 FOR UPDATE
`

// 対象 users 行をロックし、現在の account_id を読む（リンクの直列化・横取り防止）。
func (q *Queries) GetUserAccountIDForUpdate(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getUserAccountIDForUpdate, id)
	var account_id sql.NullInt64
	err := row.Scan(&account_id)
	return account_id, err
}

const isAccountDeleted = `-- name: IsAccountDeleted :one
SELECT EXISTS (SELECT 1 FROM deleted_accounts WHERE cognito_sub = $1)
`

// 削除済み sub か（墓標）。link はこれが真なら拒否する。
func (q *Queries) IsAccountDeleted(ctx context.Context, cognitoSub string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAccountDeleted, cognitoSub)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUsersByAccountID = `-- name: ListUsersByAccountID :many
SELECT id, identity_id FROM users WHERE account_id = $1 ORDER BY id
`

type ListUsersByAccountIDRow struct {
	ID         int64  `json:"id"`
	IdentityID string `json:"identity_id"`
}

// アカウントに束ねられている users 行（primary を含む全端末）。削除時に一括で消す。
// identity_id は transfer_tokens（FK 無し・文字列参照）を消すのに使う。
func (q *Queries) ListUsersByAccountID(ctx context.Context, accountID sql.NullInt64) ([]ListUsersByAccountIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByAccountIDRow{}
	for rows.Next() {
		var i ListUsersByAccountIDRow
		if err := rows.Scan(&i.ID, &i.IdentityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountSub = `-- name: LockAccountSub :exec
SELECT pg_advisory_xact_lock(hashtext($1::text))
`

// 同じ sub に対する link と delete を直列化するトランザクション内アドバイザリロック。
// 行が無い状態（削除済み・未作成）でもロックできるよう、行ロックではなくこれを使う。
func (q *Queries) LockAccountSub(ctx context.Context, cognitoSub string) error {
	_, err := q.db.ExecContext(ctx, lockAccountSub, cognitoSub)
	return err
}

const markAccountDeleted = `-- name: MarkAccountDeleted :exec
INSERT INTO deleted_accounts (cognito_sub) VALUES ($1)
ON CONFLICT (cognito_sub) DO UPDATE SET deleted_at = CURRENT_TIMESTAMP
`

func (q *Queries) MarkAccountDeleted(ctx context.Context, cognitoSub string) error {
	_, err := q.db.ExecContext(ctx, markAccountDeleted, cognitoSub)
	return err
}

const moveUserAppSettingsToUser = `-- name: MoveUserAppSettingsToUser :exec
INSERT INTO user_app_settings (user_id, app_id, selected_workbook_id, created_at, updated_at)
SELECT $1::bigint, app_id, selected_workbook_id, created_at, updated_at
FROM user_app_settings
WHERE user_id = $2::bigint
ON CONFLICT (user_id, app_id) DO NOTHING
`

type MoveUserAppSettingsToUserParams struct {
	Dst int64 `json:"dst"`
	Src int64 `json:"src"`
}

func (q *Queries) MoveUserAppSettingsToUser(ctx context.Context, arg MoveUserAppSettingsToUserParams) error {
	_, err := q.db.ExecContext(ctx, moveUserAppSettingsToUser, arg.Dst, arg.Src)
	return err
}

const purgeExpiredDeletedAccounts = `-- name: PurgeExpiredDeletedAccounts :execrows
DELETE FROM deleted_accounts WHERE deleted_at < CURRENT_TIMESTAMP - INTERVAL '7 days'
`

// 墓標は発行済み ID token（有効期間 1 時間）対策なので、余裕を見て 7 日で消す。
// 削除処理のたびに呼んで掃除する（cron を持たない）。
func (q *Queries) PurgeExpiredDeletedAccounts(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeExpiredDeletedAccounts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const repointUserAnswersToUser = `-- name: RepointUserAnswersToUser :exec
UPDATE user_answers SET user_id = $1::bigint WHERE user_id = $2::bigint
`

type RepointUserAnswersToUserParams struct {
	Dst int64 `json:"dst"`
	Src int64 `json:"src"`
}

func (q *Queries) RepointUserAnswersToUser(ctx context.Context, arg RepointUserAnswersToUserParams) error {
	_, err := q.db.ExecContext(ctx, repointUserAnswersToUser, arg.Dst, arg.Src)
	return err
}

const setUserAccountID = `-- name: SetUserAccountID :exec
UPDATE users SET account_id = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
`

type SetUserAccountIDParams struct {
	AccountID sql.NullInt64 `json:"account_id"`
	ID        int64         `json:"id"`
}

func (q *Queries) SetUserAccountID(ctx context.Context, arg SetUserAccountIDParams) error {
	_, err := q.db.ExecContext(ctx, setUserAccountID, arg.AccountID, arg.ID)
	return err
}
