// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"database/sql"
)

const createAccountIfNotExists = `-- name: CreateAccountIfNotExists :one
INSERT INTO accounts (cognito_sub, email, primary_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (cognito_sub) DO NOTHING
RETURNING id, cognito_sub, email, primary_user_id
`

type CreateAccountIfNotExistsParams struct {
	CognitoSub    string         `json:"cognito_sub"`
	Email         sql.NullString `json:"email"`
	PrimaryUserID int64          `json:"primary_user_id"`
}

type CreateAccountIfNotExistsRow struct {
	ID            int64          `json:"id"`
	CognitoSub    string         `json:"cognito_sub"`
	Email         sql.NullString `json:"email"`
	PrimaryUserID int64          `json:"primary_user_id"`
}

// 同一 sub の並行初回リンクに耐えるため ON CONFLICT DO NOTHING。
// 競合した側は行が返らない（sql.ErrNoRows）ので、呼び出し側が再取得してマージ経路へ進む。
func (q *Queries) CreateAccountIfNotExists(ctx context.Context, arg CreateAccountIfNotExistsParams) (CreateAccountIfNotExistsRow, error) {
	row := q.db.QueryRowContext(ctx, createAccountIfNotExists, arg.CognitoSub, arg.Email, arg.PrimaryUserID)
	var i CreateAccountIfNotExistsRow
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.PrimaryUserID,
	)
	return i, err
}

const deleteUserAppSettingsByUser = `-- name: DeleteUserAppSettingsByUser :exec
DELETE FROM user_app_settings WHERE user_id = $1
`

func (q *Queries) DeleteUserAppSettingsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserAppSettingsByUser, userID)
	return err
}

const getAccountByCognitoSub = `-- name: GetAccountByCognitoSub :one
SELECT id, cognito_sub, email, primary_user_id FROM accounts WHERE cognito_sub = $1
`

type GetAccountByCognitoSubRow struct {
	ID            int64          `json:"id"`
	CognitoSub    string         `json:"cognito_sub"`
	Email         sql.NullString `json:"email"`
	PrimaryUserID int64          `json:"primary_user_id"`
}

func (q *Queries) GetAccountByCognitoSub(ctx context.Context, cognitoSub string) (GetAccountByCognitoSubRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByCognitoSub, cognitoSub)
	var i GetAccountByCognitoSubRow
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.PrimaryUserID,
	)
	return i, err
}

const getPrimaryUserIDByIdentityID = `-- name: GetPrimaryUserIDByIdentityID :one
SELECT a.primary_user_id
FROM users u
JOIN accounts a ON a.id = u.account_id
WHERE u.identity_id = $1
`

// 端末が既にアカウントへ紐付いている場合の canonical user を引く。
// リンク済み端末はログアウト中でも同じアカウントへ読み書きさせるために使う
// （device user 側に回答が溜まると、再ログイン時の link は冪等 no-op なので回収されない）。
func (q *Queries) GetPrimaryUserIDByIdentityID(ctx context.Context, identityID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryUserIDByIdentityID, identityID)
	var primary_user_id int64
	err := row.Scan(&primary_user_id)
	return primary_user_id, err
}

const getUserAccountIDForUpdate = `-- name: GetUserAccountIDForUpdate :one
SELECT account_id FROM users WHERE id = $1 FOR UPDATE
`

// 対象 users 行をロックし、現在の account_id を読む（リンクの直列化・横取り防止）。
func (q *Queries) GetUserAccountIDForUpdate(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getUserAccountIDForUpdate, id)
	var account_id sql.NullInt64
	err := row.Scan(&account_id)
	return account_id, err
}

const moveUserAppSettingsToUser = `-- name: MoveUserAppSettingsToUser :exec
INSERT INTO user_app_settings (user_id, app_id, selected_workbook_id, created_at, updated_at)
SELECT $1::bigint, app_id, selected_workbook_id, created_at, updated_at
FROM user_app_settings
WHERE user_id = $2::bigint
ON CONFLICT (user_id, app_id) DO NOTHING
`

type MoveUserAppSettingsToUserParams struct {
	Dst int64 `json:"dst"`
	Src int64 `json:"src"`
}

func (q *Queries) MoveUserAppSettingsToUser(ctx context.Context, arg MoveUserAppSettingsToUserParams) error {
	_, err := q.db.ExecContext(ctx, moveUserAppSettingsToUser, arg.Dst, arg.Src)
	return err
}

const repointUserAnswersToUser = `-- name: RepointUserAnswersToUser :exec
UPDATE user_answers SET user_id = $1::bigint WHERE user_id = $2::bigint
`

type RepointUserAnswersToUserParams struct {
	Dst int64 `json:"dst"`
	Src int64 `json:"src"`
}

func (q *Queries) RepointUserAnswersToUser(ctx context.Context, arg RepointUserAnswersToUserParams) error {
	_, err := q.db.ExecContext(ctx, repointUserAnswersToUser, arg.Dst, arg.Src)
	return err
}

const setUserAccountID = `-- name: SetUserAccountID :exec
UPDATE users SET account_id = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
`

type SetUserAccountIDParams struct {
	AccountID sql.NullInt64 `json:"account_id"`
	ID        int64         `json:"id"`
}

func (q *Queries) SetUserAccountID(ctx context.Context, arg SetUserAccountIDParams) error {
	_, err := q.db.ExecContext(ctx, setUserAccountID, arg.AccountID, arg.ID)
	return err
}
