// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: announcements.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const announcementExists = `-- name: AnnouncementExists :one
SELECT EXISTS(SELECT 1 FROM announcements WHERE id = $1)
`

func (q *Queries) AnnouncementExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, announcementExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAnnouncements = `-- name: CountAnnouncements :one
SELECT COUNT(*) FROM announcements
`

func (q *Queries) CountAnnouncements(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnnouncements)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (title, body, category, published_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAnnouncementParams struct {
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	Category    string    `json:"category"`
	PublishedAt time.Time `json:"published_at"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAnnouncement,
		arg.Title,
		arg.Body,
		arg.Category,
		arg.PublishedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :execresult
DELETE FROM announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAnnouncement, id)
}

const getAnnouncement = `-- name: GetAnnouncement :one
SELECT id, title, body, category, published_at, created_at, updated_at
FROM announcements
WHERE id = $1
`

func (q *Queries) GetAnnouncement(ctx context.Context, id int64) (Announcement, error) {
	row := q.db.QueryRowContext(ctx, getAnnouncement, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Category,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, title, body, category, published_at, created_at, updated_at
FROM announcements
ORDER BY published_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAnnouncementsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.QueryContext(ctx, listAnnouncements, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Category,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAnnouncements = `-- name: ListLatestAnnouncements :many
SELECT id, title, body, category, published_at, created_at, updated_at
FROM announcements
ORDER BY published_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListLatestAnnouncements(ctx context.Context, limit int32) ([]Announcement, error) {
	rows, err := q.db.QueryContext(ctx, listLatestAnnouncements, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Category,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :exec
UPDATE announcements
SET title = $1, body = $2, category = $3, published_at = $4, updated_at = NOW()
WHERE id = $5
`

type UpdateAnnouncementParams struct {
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	Category    string    `json:"category"`
	PublishedAt time.Time `json:"published_at"`
	ID          int64     `json:"id"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) error {
	_, err := q.db.ExecContext(ctx, updateAnnouncement,
		arg.Title,
		arg.Body,
		arg.Category,
		arg.PublishedAt,
		arg.ID,
	)
	return err
}
