// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answers.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const checkAnswerCorrect = `-- name: CheckAnswerCorrect :one
SELECT EXISTS(
    SELECT 1 FROM questions_single_choice_choices c
    JOIN questions_single_choice qsc ON c.single_choice_id = qsc.id
    WHERE qsc.question_id = $1
      AND c.choice_index = $2
      AND c.is_correct = true
)
`

type CheckAnswerCorrectParams struct {
	QuestionID  int64 `json:"question_id"`
	ChoiceIndex int32 `json:"choice_index"`
}

func (q *Queries) CheckAnswerCorrect(ctx context.Context, arg CheckAnswerCorrectParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAnswerCorrect, arg.QuestionID, arg.ChoiceIndex)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUserAnswerLogs = `-- name: CountUserAnswerLogs :one
SELECT COUNT(*) FROM user_answers WHERE user_id = $1
`

func (q *Queries) CountUserAnswerLogs(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserAnswerLogs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWrongAnswers = `-- name: CountWrongAnswers :one
SELECT COUNT(*) FROM (
    SELECT DISTINCT ON (question_id) is_correct
    FROM user_answers
    WHERE user_id = $1
    ORDER BY question_id, answered_at DESC
) latest WHERE NOT is_correct
`

func (q *Queries) CountWrongAnswers(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWrongAnswers, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserAnswer = `-- name: CreateUserAnswer :exec
INSERT INTO user_answers (user_id, question_id, workbook_id, selected_choice, is_correct)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserAnswerParams struct {
	UserID         int64 `json:"user_id"`
	QuestionID     int64 `json:"question_id"`
	WorkbookID     int64 `json:"workbook_id"`
	SelectedChoice int32 `json:"selected_choice"`
	IsCorrect      bool  `json:"is_correct"`
}

func (q *Queries) CreateUserAnswer(ctx context.Context, arg CreateUserAnswerParams) error {
	_, err := q.db.ExecContext(ctx, createUserAnswer,
		arg.UserID,
		arg.QuestionID,
		arg.WorkbookID,
		arg.SelectedChoice,
		arg.IsCorrect,
	)
	return err
}

const getCorrectChoicesByQuestionIDs = `-- name: GetCorrectChoicesByQuestionIDs :many
SELECT qsc.question_id, c.choice_index
FROM questions_single_choice qsc
JOIN questions_single_choice_choices c ON c.single_choice_id = qsc.id
WHERE qsc.question_id = ANY($1::bigint[])
  AND c.is_correct = true
`

type GetCorrectChoicesByQuestionIDsRow struct {
	QuestionID  int64 `json:"question_id"`
	ChoiceIndex int32 `json:"choice_index"`
}

func (q *Queries) GetCorrectChoicesByQuestionIDs(ctx context.Context, dollar_1 []int64) ([]GetCorrectChoicesByQuestionIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCorrectChoicesByQuestionIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCorrectChoicesByQuestionIDsRow{}
	for rows.Next() {
		var i GetCorrectChoicesByQuestionIDsRow
		if err := rows.Scan(&i.QuestionID, &i.ChoiceIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByIdentityID = `-- name: GetUserByIdentityID :one
SELECT id FROM users WHERE identity_id = $1
`

func (q *Queries) GetUserByIdentityID(ctx context.Context, identityID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserByIdentityID, identityID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserTotalStats = `-- name: GetUserTotalStats :one
SELECT
    COUNT(*)::int AS total_answered,
    COALESCE(SUM(CASE WHEN is_correct THEN 1 ELSE 0 END), 0)::int AS total_correct
FROM user_answers
WHERE user_id = $1
`

type GetUserTotalStatsRow struct {
	TotalAnswered int32 `json:"total_answered"`
	TotalCorrect  int32 `json:"total_correct"`
}

func (q *Queries) GetUserTotalStats(ctx context.Context, userID int64) (GetUserTotalStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserTotalStats, userID)
	var i GetUserTotalStatsRow
	err := row.Scan(&i.TotalAnswered, &i.TotalCorrect)
	return i, err
}

const getUserWeeklyStats = `-- name: GetUserWeeklyStats :one
SELECT
    COUNT(*)::int AS weekly_answered,
    COALESCE(SUM(CASE WHEN is_correct THEN 1 ELSE 0 END), 0)::int AS weekly_correct
FROM user_answers
WHERE user_id = $1 AND answered_at >= $2
`

type GetUserWeeklyStatsParams struct {
	UserID     int64        `json:"user_id"`
	AnsweredAt sql.NullTime `json:"answered_at"`
}

type GetUserWeeklyStatsRow struct {
	WeeklyAnswered int32 `json:"weekly_answered"`
	WeeklyCorrect  int32 `json:"weekly_correct"`
}

func (q *Queries) GetUserWeeklyStats(ctx context.Context, arg GetUserWeeklyStatsParams) (GetUserWeeklyStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWeeklyStats, arg.UserID, arg.AnsweredAt)
	var i GetUserWeeklyStatsRow
	err := row.Scan(&i.WeeklyAnswered, &i.WeeklyCorrect)
	return i, err
}

const listStudyDates = `-- name: ListStudyDates :many
SELECT DISTINCT DATE(answered_at)::text AS study_date
FROM user_answers
WHERE user_id = $1
ORDER BY study_date DESC
LIMIT 365
`

func (q *Queries) ListStudyDates(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listStudyDates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var study_date string
		if err := rows.Scan(&study_date); err != nil {
			return nil, err
		}
		items = append(items, study_date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAnswerLogs = `-- name: ListUserAnswerLogs :many
SELECT ua.id, ua.question_id, qsc.text AS question_text,
       ua.workbook_id, w.title AS workbook_title,
       ua.selected_choice, ua.is_correct, ua.answered_at
FROM user_answers ua
JOIN questions q ON q.id = ua.question_id
JOIN questions_single_choice qsc ON q.id = qsc.question_id
JOIN workbooks w ON w.id = ua.workbook_id
WHERE ua.user_id = $1
ORDER BY ua.answered_at DESC
LIMIT $2 OFFSET $3
`

type ListUserAnswerLogsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUserAnswerLogsRow struct {
	ID             int64        `json:"id"`
	QuestionID     int64        `json:"question_id"`
	QuestionText   string       `json:"question_text"`
	WorkbookID     int64        `json:"workbook_id"`
	WorkbookTitle  string       `json:"workbook_title"`
	SelectedChoice int32        `json:"selected_choice"`
	IsCorrect      bool         `json:"is_correct"`
	AnsweredAt     sql.NullTime `json:"answered_at"`
}

func (q *Queries) ListUserAnswerLogs(ctx context.Context, arg ListUserAnswerLogsParams) ([]ListUserAnswerLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserAnswerLogs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAnswerLogsRow{}
	for rows.Next() {
		var i ListUserAnswerLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.QuestionText,
			&i.WorkbookID,
			&i.WorkbookTitle,
			&i.SelectedChoice,
			&i.IsCorrect,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, identity_id, display_name, created_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID          int64          `json:"id"`
	IdentityID  string         `json:"identity_id"`
	DisplayName sql.NullString `json:"display_name"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeklyWorkbookIDs = `-- name: ListWeeklyWorkbookIDs :many
SELECT DISTINCT workbook_id
FROM user_answers
WHERE user_id = $1 AND answered_at >= $2
`

type ListWeeklyWorkbookIDsParams struct {
	UserID     int64        `json:"user_id"`
	AnsweredAt sql.NullTime `json:"answered_at"`
}

func (q *Queries) ListWeeklyWorkbookIDs(ctx context.Context, arg ListWeeklyWorkbookIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listWeeklyWorkbookIDs, arg.UserID, arg.AnsweredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var workbook_id int64
		if err := rows.Scan(&workbook_id); err != nil {
			return nil, err
		}
		items = append(items, workbook_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkbookProgress = `-- name: ListWorkbookProgress :many
SELECT DISTINCT ON (question_id) question_id, is_correct
FROM user_answers
WHERE user_id = $1 AND workbook_id = $2
ORDER BY question_id, answered_at DESC
`

type ListWorkbookProgressParams struct {
	UserID     int64 `json:"user_id"`
	WorkbookID int64 `json:"workbook_id"`
}

type ListWorkbookProgressRow struct {
	QuestionID int64 `json:"question_id"`
	IsCorrect  bool  `json:"is_correct"`
}

func (q *Queries) ListWorkbookProgress(ctx context.Context, arg ListWorkbookProgressParams) ([]ListWorkbookProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkbookProgress, arg.UserID, arg.WorkbookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkbookProgressRow{}
	for rows.Next() {
		var i ListWorkbookProgressRow
		if err := rows.Scan(&i.QuestionID, &i.IsCorrect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWrongAnswers = `-- name: ListWrongAnswers :many
SELECT q.id, qsc.text, qsc.explanation
FROM (
    SELECT DISTINCT ON (question_id) question_id, is_correct
    FROM user_answers
    WHERE user_id = $1
    ORDER BY question_id, answered_at DESC
) latest
JOIN questions q ON q.id = latest.question_id
JOIN questions_single_choice qsc ON q.id = qsc.question_id
WHERE NOT latest.is_correct
ORDER BY q.id
LIMIT $2 OFFSET $3
`

type ListWrongAnswersParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListWrongAnswersRow struct {
	ID          int64          `json:"id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
}

func (q *Queries) ListWrongAnswers(ctx context.Context, arg ListWrongAnswersParams) ([]ListWrongAnswersRow, error) {
	rows, err := q.db.QueryContext(ctx, listWrongAnswers, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWrongAnswersRow{}
	for rows.Next() {
		var i ListWrongAnswersRow
		if err := rows.Scan(&i.ID, &i.Text, &i.Explanation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWrongAnswersWithChoices = `-- name: ListWrongAnswersWithChoices :many
SELECT q.id, qsc.text, qsc.explanation,
    c.text AS choice_text, c.is_correct, c.choice_index
FROM (
    SELECT question_id FROM (
        SELECT DISTINCT ON (question_id) question_id, is_correct
        FROM user_answers
        WHERE user_id = $1
        ORDER BY question_id, answered_at DESC
    ) latest
    WHERE NOT is_correct
    ORDER BY question_id
    LIMIT $2 OFFSET $3
) paged
JOIN questions q ON q.id = paged.question_id
JOIN questions_single_choice qsc ON q.id = qsc.question_id
LEFT JOIN questions_single_choice_choices c ON c.single_choice_id = qsc.id
ORDER BY q.id, c.choice_index
`

type ListWrongAnswersWithChoicesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListWrongAnswersWithChoicesRow struct {
	ID          int64          `json:"id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
	ChoiceText  sql.NullString `json:"choice_text"`
	IsCorrect   sql.NullBool   `json:"is_correct"`
	ChoiceIndex sql.NullInt32  `json:"choice_index"`
}

func (q *Queries) ListWrongAnswersWithChoices(ctx context.Context, arg ListWrongAnswersWithChoicesParams) ([]ListWrongAnswersWithChoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWrongAnswersWithChoices, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWrongAnswersWithChoicesRow{}
	for rows.Next() {
		var i ListWrongAnswersWithChoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Explanation,
			&i.ChoiceText,
			&i.IsCorrect,
			&i.ChoiceIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (identity_id) VALUES ($1)
ON CONFLICT (identity_id) DO UPDATE SET updated_at = CURRENT_TIMESTAMP
RETURNING id
`

func (q *Queries) UpsertUser(ctx context.Context, identityID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, identityID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
