// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answers.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const checkAnswerCorrect = `-- name: CheckAnswerCorrect :one
SELECT EXISTS(
    SELECT 1 FROM questions_single_choice_choices c
    JOIN questions_single_choice qsc ON c.single_choice_id = qsc.id
    WHERE qsc.question_id = $1
      AND c.choice_index = $2
      AND c.is_correct = true
)
`

type CheckAnswerCorrectParams struct {
	QuestionID  int64 `json:"question_id"`
	ChoiceIndex int32 `json:"choice_index"`
}

func (q *Queries) CheckAnswerCorrect(ctx context.Context, arg CheckAnswerCorrectParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAnswerCorrect, arg.QuestionID, arg.ChoiceIndex)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWrongAnswers = `-- name: CountWrongAnswers :one
SELECT COUNT(*) FROM (
    SELECT DISTINCT ON (question_id) is_correct
    FROM user_answers
    WHERE user_id = $1
    ORDER BY question_id, answered_at DESC
) latest WHERE NOT is_correct
`

func (q *Queries) CountWrongAnswers(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWrongAnswers, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserAnswer = `-- name: CreateUserAnswer :exec
INSERT INTO user_answers (user_id, question_id, workbook_id, selected_choice, is_correct)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserAnswerParams struct {
	UserID         int64 `json:"user_id"`
	QuestionID     int64 `json:"question_id"`
	WorkbookID     int64 `json:"workbook_id"`
	SelectedChoice int32 `json:"selected_choice"`
	IsCorrect      bool  `json:"is_correct"`
}

func (q *Queries) CreateUserAnswer(ctx context.Context, arg CreateUserAnswerParams) error {
	_, err := q.db.ExecContext(ctx, createUserAnswer,
		arg.UserID,
		arg.QuestionID,
		arg.WorkbookID,
		arg.SelectedChoice,
		arg.IsCorrect,
	)
	return err
}

const getCorrectChoicesByQuestionIDs = `-- name: GetCorrectChoicesByQuestionIDs :many
SELECT qsc.question_id, c.choice_index
FROM questions_single_choice qsc
JOIN questions_single_choice_choices c ON c.single_choice_id = qsc.id
WHERE qsc.question_id = ANY($1::bigint[])
  AND c.is_correct = true
`

type GetCorrectChoicesByQuestionIDsRow struct {
	QuestionID  int64 `json:"question_id"`
	ChoiceIndex int32 `json:"choice_index"`
}

func (q *Queries) GetCorrectChoicesByQuestionIDs(ctx context.Context, dollar_1 []int64) ([]GetCorrectChoicesByQuestionIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCorrectChoicesByQuestionIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCorrectChoicesByQuestionIDsRow{}
	for rows.Next() {
		var i GetCorrectChoicesByQuestionIDsRow
		if err := rows.Scan(&i.QuestionID, &i.ChoiceIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByIdentityID = `-- name: GetUserByIdentityID :one
SELECT id FROM users WHERE identity_id = $1
`

func (q *Queries) GetUserByIdentityID(ctx context.Context, identityID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserByIdentityID, identityID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, identity_id, created_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID         int64        `json:"id"`
	IdentityID string       `json:"identity_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.IdentityID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWrongAnswers = `-- name: ListWrongAnswers :many
SELECT q.id, qsc.text, qsc.explanation
FROM (
    SELECT DISTINCT ON (question_id) question_id, is_correct
    FROM user_answers
    WHERE user_id = $1
    ORDER BY question_id, answered_at DESC
) latest
JOIN questions q ON q.id = latest.question_id
JOIN questions_single_choice qsc ON q.id = qsc.question_id
WHERE NOT latest.is_correct
ORDER BY q.id
LIMIT $2 OFFSET $3
`

type ListWrongAnswersParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListWrongAnswersRow struct {
	ID          int64          `json:"id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
}

func (q *Queries) ListWrongAnswers(ctx context.Context, arg ListWrongAnswersParams) ([]ListWrongAnswersRow, error) {
	rows, err := q.db.QueryContext(ctx, listWrongAnswers, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWrongAnswersRow{}
	for rows.Next() {
		var i ListWrongAnswersRow
		if err := rows.Scan(&i.ID, &i.Text, &i.Explanation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWrongAnswersWithChoices = `-- name: ListWrongAnswersWithChoices :many
SELECT q.id, qsc.text, qsc.explanation,
    c.text AS choice_text, c.is_correct, c.choice_index
FROM (
    SELECT question_id FROM (
        SELECT DISTINCT ON (question_id) question_id, is_correct
        FROM user_answers
        WHERE user_id = $1
        ORDER BY question_id, answered_at DESC
    ) latest
    WHERE NOT is_correct
    ORDER BY question_id
    LIMIT $2 OFFSET $3
) paged
JOIN questions q ON q.id = paged.question_id
JOIN questions_single_choice qsc ON q.id = qsc.question_id
LEFT JOIN questions_single_choice_choices c ON c.single_choice_id = qsc.id
ORDER BY q.id, c.choice_index
`

type ListWrongAnswersWithChoicesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListWrongAnswersWithChoicesRow struct {
	ID          int64          `json:"id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
	ChoiceText  sql.NullString `json:"choice_text"`
	IsCorrect   sql.NullBool   `json:"is_correct"`
	ChoiceIndex sql.NullInt32  `json:"choice_index"`
}

func (q *Queries) ListWrongAnswersWithChoices(ctx context.Context, arg ListWrongAnswersWithChoicesParams) ([]ListWrongAnswersWithChoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWrongAnswersWithChoices, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWrongAnswersWithChoicesRow{}
	for rows.Next() {
		var i ListWrongAnswersWithChoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Explanation,
			&i.ChoiceText,
			&i.IsCorrect,
			&i.ChoiceIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (identity_id) VALUES ($1)
ON CONFLICT (identity_id) DO UPDATE SET updated_at = CURRENT_TIMESTAMP
RETURNING id
`

func (q *Queries) UpsertUser(ctx context.Context, identityID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, identityID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
