// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_status.sql

package db

import (
	"context"
	"time"
)

const getAppStatus = `-- name: GetAppStatus :one
SELECT is_maintenance, maintenance_message, updated_at FROM app_status WHERE id = TRUE
`

type GetAppStatusRow struct {
	IsMaintenance      bool      `json:"is_maintenance"`
	MaintenanceMessage string    `json:"maintenance_message"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) GetAppStatus(ctx context.Context) (GetAppStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getAppStatus)
	var i GetAppStatusRow
	err := row.Scan(&i.IsMaintenance, &i.MaintenanceMessage, &i.UpdatedAt)
	return i, err
}

const updateAppStatus = `-- name: UpdateAppStatus :exec
UPDATE app_status
SET is_maintenance = $1, maintenance_message = $2, updated_at = NOW()
WHERE id = TRUE
`

type UpdateAppStatusParams struct {
	IsMaintenance      bool   `json:"is_maintenance"`
	MaintenanceMessage string `json:"maintenance_message"`
}

func (q *Queries) UpdateAppStatus(ctx context.Context, arg UpdateAppStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAppStatus, arg.IsMaintenance, arg.MaintenanceMessage)
	return err
}
