// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package db

import (
	"context"
	"database/sql"
)

const countApps = `-- name: CountApps :one
SELECT COUNT(*) FROM apps
`

func (q *Queries) CountApps(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps (slug, title) VALUES ($1, $2) RETURNING id
`

type CreateAppParams struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createApp, arg.Slug, arg.Title)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteApp = `-- name: DeleteApp :execresult
DELETE FROM apps WHERE id = $1
`

func (q *Queries) DeleteApp(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteApp, id)
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, slug, title, created_at FROM apps WHERE id = $1
`

func (q *Queries) GetAppByID(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getAppBySlug = `-- name: GetAppBySlug :one
SELECT id, slug, title FROM apps WHERE slug = $1
`

type GetAppBySlugRow struct {
	ID    int64  `json:"id"`
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

func (q *Queries) GetAppBySlug(ctx context.Context, slug string) (GetAppBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getAppBySlug, slug)
	var i GetAppBySlugRow
	err := row.Scan(&i.ID, &i.Slug, &i.Title)
	return i, err
}

const getUserAppSetting = `-- name: GetUserAppSetting :one
SELECT uas.id, uas.selected_workbook_id, uas.created_at, uas.updated_at
FROM user_app_settings uas
WHERE uas.user_id = $1 AND uas.app_id = $2
`

type GetUserAppSettingParams struct {
	UserID int64 `json:"user_id"`
	AppID  int64 `json:"app_id"`
}

type GetUserAppSettingRow struct {
	ID                 int64         `json:"id"`
	SelectedWorkbookID sql.NullInt64 `json:"selected_workbook_id"`
	CreatedAt          sql.NullTime  `json:"created_at"`
	UpdatedAt          sql.NullTime  `json:"updated_at"`
}

func (q *Queries) GetUserAppSetting(ctx context.Context, arg GetUserAppSettingParams) (GetUserAppSettingRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAppSetting, arg.UserID, arg.AppID)
	var i GetUserAppSettingRow
	err := row.Scan(
		&i.ID,
		&i.SelectedWorkbookID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, identity_id, display_name, created_at FROM users WHERE id = $1
`

type GetUserProfileRow struct {
	ID          int64          `json:"id"`
	IdentityID  string         `json:"identity_id"`
	DisplayName sql.NullString `json:"display_name"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetUserProfile(ctx context.Context, id int64) (GetUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT id, slug, title, created_at FROM apps ORDER BY id
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAppSettings = `-- name: ListUserAppSettings :many
SELECT uas.id, a.slug AS app_slug, a.title AS app_title, uas.selected_workbook_id, uas.updated_at
FROM user_app_settings uas
JOIN apps a ON a.id = uas.app_id
WHERE uas.user_id = $1
ORDER BY a.id
`

type ListUserAppSettingsRow struct {
	ID                 int64         `json:"id"`
	AppSlug            string        `json:"app_slug"`
	AppTitle           string        `json:"app_title"`
	SelectedWorkbookID sql.NullInt64 `json:"selected_workbook_id"`
	UpdatedAt          sql.NullTime  `json:"updated_at"`
}

func (q *Queries) ListUserAppSettings(ctx context.Context, userID int64) ([]ListUserAppSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserAppSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAppSettingsRow{}
	for rows.Next() {
		var i ListUserAppSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppSlug,
			&i.AppTitle,
			&i.SelectedWorkbookID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :exec
UPDATE apps SET slug = $1, title = $2 WHERE id = $3
`

type UpdateAppParams struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) error {
	_, err := q.db.ExecContext(ctx, updateApp, arg.Slug, arg.Title, arg.ID)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users SET display_name = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
`

type UpdateUserDisplayNameParams struct {
	DisplayName sql.NullString `json:"display_name"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDisplayName, arg.DisplayName, arg.ID)
	return err
}

const upsertUserAppSetting = `-- name: UpsertUserAppSetting :exec
INSERT INTO user_app_settings (user_id, app_id, selected_workbook_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, app_id) DO UPDATE SET
    selected_workbook_id = $3,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertUserAppSettingParams struct {
	UserID             int64         `json:"user_id"`
	AppID              int64         `json:"app_id"`
	SelectedWorkbookID sql.NullInt64 `json:"selected_workbook_id"`
}

func (q *Queries) UpsertUserAppSetting(ctx context.Context, arg UpsertUserAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserAppSetting, arg.UserID, arg.AppID, arg.SelectedWorkbookID)
	return err
}
