// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"
	"database/sql"
)

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS(SELECT 1 FROM categories WHERE id = $1)
`

func (q *Queries) CategoryExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, categoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (title, description) VALUES ($1, $2) RETURNING id
`

type CreateCategoryParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Title, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCategory = `-- name: DeleteCategory :execresult
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCategory, id)
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, title, description FROM categories WHERE id = $1
`

type GetCategoryByIDRow struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (GetCategoryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i GetCategoryByIDRow
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const getCategoryTitle = `-- name: GetCategoryTitle :one
SELECT title, description FROM categories WHERE id = $1
`

type GetCategoryTitleRow struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) GetCategoryTitle(ctx context.Context, id int64) (GetCategoryTitleRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryTitle, id)
	var i GetCategoryTitleRow
	err := row.Scan(&i.Title, &i.Description)
	return i, err
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT c.id, c.title, c.description,
    (SELECT COUNT(*) FROM workbooks w WHERE w.category_id = c.id) as workbook_count
FROM categories c
ORDER BY c.id
`

type ListAllCategoriesRow struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	WorkbookCount int64          `json:"workbook_count"`
}

func (q *Queries) ListAllCategories(ctx context.Context) ([]ListAllCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCategoriesRow{}
	for rows.Next() {
		var i ListAllCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.WorkbookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT c.id, c.title, c.description,
    (SELECT COUNT(*) FROM workbooks w WHERE w.category_id = c.id) as workbook_count
FROM categories c
ORDER BY c.id
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCategoriesRow struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	WorkbookCount int64          `json:"workbook_count"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.WorkbookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkbooksByCategory = `-- name: ListWorkbooksByCategory :many
SELECT w.id, w.title, w.description,
    (SELECT COUNT(*) FROM workbook_questions wq WHERE wq.workbook_id = w.id) as question_count
FROM workbooks w
WHERE w.category_id = $1
ORDER BY w.id
`

type ListWorkbooksByCategoryRow struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	QuestionCount int64          `json:"question_count"`
}

func (q *Queries) ListWorkbooksByCategory(ctx context.Context, categoryID sql.NullInt64) ([]ListWorkbooksByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkbooksByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkbooksByCategoryRow{}
	for rows.Next() {
		var i ListWorkbooksByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET title = $1, description = $2, updated_at = $3 WHERE id = $4
`

type UpdateCategoryParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Title,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
