// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (path) VALUES ($1) RETURNING id
`

func (q *Queries) CreateImage(ctx context.Context, path string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createImage, path)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createQuestionImage = `-- name: CreateQuestionImage :exec
INSERT INTO question_images (question_id, image_id, order_index) VALUES ($1, $2, $3)
`

type CreateQuestionImageParams struct {
	QuestionID int64 `json:"question_id"`
	ImageID    int64 `json:"image_id"`
	OrderIndex int32 `json:"order_index"`
}

func (q *Queries) CreateQuestionImage(ctx context.Context, arg CreateQuestionImageParams) error {
	_, err := q.db.ExecContext(ctx, createQuestionImage, arg.QuestionID, arg.ImageID, arg.OrderIndex)
	return err
}

const deleteQuestionImages = `-- name: DeleteQuestionImages :exec
DELETE FROM question_images WHERE question_id = $1
`

func (q *Queries) DeleteQuestionImages(ctx context.Context, questionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionImages, questionID)
	return err
}

const getImageURLsByQuestionID = `-- name: GetImageURLsByQuestionID :many
SELECT i.path
FROM images i
JOIN question_images qi ON i.id = qi.image_id
WHERE qi.question_id = $1
ORDER BY qi.order_index
`

func (q *Queries) GetImageURLsByQuestionID(ctx context.Context, questionID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getImageURLsByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageURLsByQuestionIDs = `-- name: GetImageURLsByQuestionIDs :many
SELECT qi.question_id, i.path
FROM question_images qi
JOIN images i ON i.id = qi.image_id
WHERE qi.question_id = ANY($1::bigint[])
ORDER BY qi.question_id, qi.order_index
`

type GetImageURLsByQuestionIDsRow struct {
	QuestionID int64  `json:"question_id"`
	Path       string `json:"path"`
}

func (q *Queries) GetImageURLsByQuestionIDs(ctx context.Context, dollar_1 []int64) ([]GetImageURLsByQuestionIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getImageURLsByQuestionIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetImageURLsByQuestionIDsRow{}
	for rows.Next() {
		var i GetImageURLsByQuestionIDsRow
		if err := rows.Scan(&i.QuestionID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
