// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: importer.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAllCategories = `-- name: DeleteAllCategories :exec
DELETE FROM categories
`

func (q *Queries) DeleteAllCategories(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCategories)
	return err
}

const deleteAllChoices = `-- name: DeleteAllChoices :exec
DELETE FROM questions_single_choice_choices
`

func (q *Queries) DeleteAllChoices(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllChoices)
	return err
}

const deleteAllImages = `-- name: DeleteAllImages :exec
DELETE FROM images
`

func (q *Queries) DeleteAllImages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllImages)
	return err
}

const deleteAllQuestionImages = `-- name: DeleteAllQuestionImages :exec
DELETE FROM question_images
`

func (q *Queries) DeleteAllQuestionImages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllQuestionImages)
	return err
}

const deleteAllQuestions = `-- name: DeleteAllQuestions :exec
DELETE FROM questions
`

func (q *Queries) DeleteAllQuestions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllQuestions)
	return err
}

const deleteAllSingleChoices = `-- name: DeleteAllSingleChoices :exec
DELETE FROM questions_single_choice
`

func (q *Queries) DeleteAllSingleChoices(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSingleChoices)
	return err
}

const deleteAllWorkbookQuestions = `-- name: DeleteAllWorkbookQuestions :exec
DELETE FROM workbook_questions
`

func (q *Queries) DeleteAllWorkbookQuestions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllWorkbookQuestions)
	return err
}

const deleteAllWorkbooks = `-- name: DeleteAllWorkbooks :exec
DELETE FROM workbooks
`

func (q *Queries) DeleteAllWorkbooks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllWorkbooks)
	return err
}

const importCategory = `-- name: ImportCategory :exec
INSERT INTO categories (id, title, description) VALUES ($1, $2, $3)
`

type ImportCategoryParams struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) ImportCategory(ctx context.Context, arg ImportCategoryParams) error {
	_, err := q.db.ExecContext(ctx, importCategory, arg.ID, arg.Title, arg.Description)
	return err
}

const importChoice = `-- name: ImportChoice :exec
INSERT INTO questions_single_choice_choices (single_choice_id, choice_index, text, is_correct)
VALUES ($1, $2, $3, $4)
`

type ImportChoiceParams struct {
	SingleChoiceID int64  `json:"single_choice_id"`
	ChoiceIndex    int32  `json:"choice_index"`
	Text           string `json:"text"`
	IsCorrect      bool   `json:"is_correct"`
}

func (q *Queries) ImportChoice(ctx context.Context, arg ImportChoiceParams) error {
	_, err := q.db.ExecContext(ctx, importChoice,
		arg.SingleChoiceID,
		arg.ChoiceIndex,
		arg.Text,
		arg.IsCorrect,
	)
	return err
}

const importImage = `-- name: ImportImage :exec
INSERT INTO images (id, path) VALUES ($1, $2)
`

type ImportImageParams struct {
	ID   int64  `json:"id"`
	Path string `json:"path"`
}

func (q *Queries) ImportImage(ctx context.Context, arg ImportImageParams) error {
	_, err := q.db.ExecContext(ctx, importImage, arg.ID, arg.Path)
	return err
}

const importQuestion = `-- name: ImportQuestion :exec
INSERT INTO questions (id, type) VALUES ($1, $2)
`

type ImportQuestionParams struct {
	ID   int64  `json:"id"`
	Type string `json:"type"`
}

func (q *Queries) ImportQuestion(ctx context.Context, arg ImportQuestionParams) error {
	_, err := q.db.ExecContext(ctx, importQuestion, arg.ID, arg.Type)
	return err
}

const importQuestionImage = `-- name: ImportQuestionImage :exec
INSERT INTO question_images (question_id, image_id, order_index) VALUES ($1, $2, $3)
`

type ImportQuestionImageParams struct {
	QuestionID int64 `json:"question_id"`
	ImageID    int64 `json:"image_id"`
	OrderIndex int32 `json:"order_index"`
}

func (q *Queries) ImportQuestionImage(ctx context.Context, arg ImportQuestionImageParams) error {
	_, err := q.db.ExecContext(ctx, importQuestionImage, arg.QuestionID, arg.ImageID, arg.OrderIndex)
	return err
}

const importSingleChoice = `-- name: ImportSingleChoice :one
INSERT INTO questions_single_choice (question_id, text, explanation)
VALUES ($1, $2, $3) RETURNING id
`

type ImportSingleChoiceParams struct {
	QuestionID  int64          `json:"question_id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
}

func (q *Queries) ImportSingleChoice(ctx context.Context, arg ImportSingleChoiceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importSingleChoice, arg.QuestionID, arg.Text, arg.Explanation)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importWorkbook = `-- name: ImportWorkbook :exec
INSERT INTO workbooks (id, title, description) VALUES ($1, $2, $3)
`

type ImportWorkbookParams struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) ImportWorkbook(ctx context.Context, arg ImportWorkbookParams) error {
	_, err := q.db.ExecContext(ctx, importWorkbook, arg.ID, arg.Title, arg.Description)
	return err
}

const importWorkbookQuestion = `-- name: ImportWorkbookQuestion :exec
INSERT INTO workbook_questions (workbook_id, question_id, order_index) VALUES ($1, $2, $3)
`

type ImportWorkbookQuestionParams struct {
	WorkbookID int64 `json:"workbook_id"`
	QuestionID int64 `json:"question_id"`
	OrderIndex int32 `json:"order_index"`
}

func (q *Queries) ImportWorkbookQuestion(ctx context.Context, arg ImportWorkbookQuestionParams) error {
	_, err := q.db.ExecContext(ctx, importWorkbookQuestion, arg.WorkbookID, arg.QuestionID, arg.OrderIndex)
	return err
}

const setWorkbookCategory = `-- name: SetWorkbookCategory :exec
UPDATE workbooks SET category_id = $1 WHERE id = $2
`

type SetWorkbookCategoryParams struct {
	CategoryID sql.NullInt64 `json:"category_id"`
	ID         int64         `json:"id"`
}

func (q *Queries) SetWorkbookCategory(ctx context.Context, arg SetWorkbookCategoryParams) error {
	_, err := q.db.ExecContext(ctx, setWorkbookCategory, arg.CategoryID, arg.ID)
	return err
}
