// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Announcement struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	Category    string    `json:"category"`
	PublishedAt time.Time `json:"published_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type App struct {
	ID        int64        `json:"id"`
	Slug      string       `json:"slug"`
	Title     string       `json:"title"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type AppStatus struct {
	ID                 bool      `json:"id"`
	IsMaintenance      bool      `json:"is_maintenance"`
	MaintenanceMessage string    `json:"maintenance_message"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type Category struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Image struct {
	ID        int64        `json:"id"`
	Path      string       `json:"path"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Question struct {
	ID        int64        `json:"id"`
	Type      string       `json:"type"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type QuestionImage struct {
	QuestionID int64 `json:"question_id"`
	ImageID    int64 `json:"image_id"`
	OrderIndex int32 `json:"order_index"`
}

type QuestionsSingleChoice struct {
	ID          int64          `json:"id"`
	QuestionID  int64          `json:"question_id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type QuestionsSingleChoiceChoice struct {
	ID             int64  `json:"id"`
	SingleChoiceID int64  `json:"single_choice_id"`
	ChoiceIndex    int32  `json:"choice_index"`
	Text           string `json:"text"`
	IsCorrect      bool   `json:"is_correct"`
}

type User struct {
	ID          int64          `json:"id"`
	IdentityID  string         `json:"identity_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DisplayName sql.NullString `json:"display_name"`
}

type UserAnswer struct {
	ID             int64        `json:"id"`
	UserID         int64        `json:"user_id"`
	QuestionID     int64        `json:"question_id"`
	WorkbookID     int64        `json:"workbook_id"`
	SelectedChoice int32        `json:"selected_choice"`
	IsCorrect      bool         `json:"is_correct"`
	AnsweredAt     sql.NullTime `json:"answered_at"`
}

type UserAppSetting struct {
	ID                 int64         `json:"id"`
	UserID             int64         `json:"user_id"`
	AppID              int64         `json:"app_id"`
	SelectedWorkbookID sql.NullInt64 `json:"selected_workbook_id"`
	CreatedAt          sql.NullTime  `json:"created_at"`
	UpdatedAt          sql.NullTime  `json:"updated_at"`
}

type Workbook struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CategoryID  sql.NullInt64  `json:"category_id"`
}

type WorkbookQuestion struct {
	WorkbookID int64 `json:"workbook_id"`
	QuestionID int64 `json:"question_id"`
	OrderIndex int32 `json:"order_index"`
}
