// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CategoryExists(ctx context.Context, id int64) (bool, error)
	CheckAnswerCorrect(ctx context.Context, arg CheckAnswerCorrectParams) (bool, error)
	CountCategories(ctx context.Context) (int64, error)
	CountQuestions(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkbooks(ctx context.Context) (int64, error)
	CountWrongAnswers(ctx context.Context, userID int64) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error)
	CreateChoice(ctx context.Context, arg CreateChoiceParams) error
	CreateImage(ctx context.Context, path string) (int64, error)
	CreateQuestion(ctx context.Context, type_ string) (int64, error)
	CreateQuestionImage(ctx context.Context, arg CreateQuestionImageParams) error
	CreateSingleChoice(ctx context.Context, arg CreateSingleChoiceParams) (int64, error)
	CreateUserAnswer(ctx context.Context, arg CreateUserAnswerParams) error
	CreateWorkbook(ctx context.Context, arg CreateWorkbookParams) (int64, error)
	CreateWorkbookQuestion(ctx context.Context, arg CreateWorkbookQuestionParams) error
	DeleteAllCategories(ctx context.Context) error
	DeleteAllChoices(ctx context.Context) error
	DeleteAllImages(ctx context.Context) error
	DeleteAllQuestionImages(ctx context.Context) error
	DeleteAllQuestions(ctx context.Context) error
	DeleteAllSingleChoices(ctx context.Context) error
	DeleteAllWorkbookQuestions(ctx context.Context) error
	DeleteAllWorkbooks(ctx context.Context) error
	DeleteCategory(ctx context.Context, id int64) (sql.Result, error)
	DeleteChoicesByQuestionID(ctx context.Context, questionID int64) error
	DeleteQuestion(ctx context.Context, id int64) (sql.Result, error)
	DeleteQuestionImages(ctx context.Context, questionID int64) error
	DeleteWorkbook(ctx context.Context, id int64) (sql.Result, error)
	DeleteWorkbookQuestions(ctx context.Context, workbookID int64) error
	GetCategoryByID(ctx context.Context, id int64) (GetCategoryByIDRow, error)
	GetCategoryTitle(ctx context.Context, id int64) (GetCategoryTitleRow, error)
	GetChoicesByQuestionID(ctx context.Context, questionID int64) ([]GetChoicesByQuestionIDRow, error)
	GetCorrectChoicesByQuestionIDs(ctx context.Context, dollar_1 []int64) ([]GetCorrectChoicesByQuestionIDsRow, error)
	GetImageURLsByQuestionID(ctx context.Context, questionID int64) ([]string, error)
	GetImageURLsByQuestionIDs(ctx context.Context, dollar_1 []int64) ([]GetImageURLsByQuestionIDsRow, error)
	GetQuestionByID(ctx context.Context, id int64) (GetQuestionByIDRow, error)
	GetSingleChoiceID(ctx context.Context, questionID int64) (int64, error)
	GetUserByIdentityID(ctx context.Context, identityID string) (int64, error)
	GetWorkbookByID(ctx context.Context, id int64) (GetWorkbookByIDRow, error)
	GetWorkbookTitle(ctx context.Context, id int64) (GetWorkbookTitleRow, error)
	ImportCategory(ctx context.Context, arg ImportCategoryParams) error
	ImportChoice(ctx context.Context, arg ImportChoiceParams) error
	ImportImage(ctx context.Context, arg ImportImageParams) error
	ImportQuestion(ctx context.Context, arg ImportQuestionParams) error
	ImportQuestionImage(ctx context.Context, arg ImportQuestionImageParams) error
	ImportSingleChoice(ctx context.Context, arg ImportSingleChoiceParams) (int64, error)
	ImportWorkbook(ctx context.Context, arg ImportWorkbookParams) error
	ImportWorkbookQuestion(ctx context.Context, arg ImportWorkbookQuestionParams) error
	ListAllCategories(ctx context.Context) ([]ListAllCategoriesRow, error)
	ListAllWorkbooks(ctx context.Context) ([]ListAllWorkbooksRow, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error)
	ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]ListQuestionsRow, error)
	ListQuestionsByWorkbook(ctx context.Context, workbookID int64) ([]ListQuestionsByWorkbookRow, error)
	ListQuestionsWithChoices(ctx context.Context, arg ListQuestionsWithChoicesParams) ([]ListQuestionsWithChoicesRow, error)
	ListQuestionsWithChoicesByWorkbook(ctx context.Context, workbookID int64) ([]ListQuestionsWithChoicesByWorkbookRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListWorkbooks(ctx context.Context, arg ListWorkbooksParams) ([]ListWorkbooksRow, error)
	ListWorkbooksByCategory(ctx context.Context, categoryID sql.NullInt64) ([]ListWorkbooksByCategoryRow, error)
	ListWrongAnswers(ctx context.Context, arg ListWrongAnswersParams) ([]ListWrongAnswersRow, error)
	ListWrongAnswersWithChoices(ctx context.Context, arg ListWrongAnswersWithChoicesParams) ([]ListWrongAnswersWithChoicesRow, error)
	QuestionExists(ctx context.Context, id int64) (bool, error)
	SetWorkbookCategory(ctx context.Context, arg SetWorkbookCategoryParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateQuestionTimestamp(ctx context.Context, arg UpdateQuestionTimestampParams) error
	UpdateSingleChoice(ctx context.Context, arg UpdateSingleChoiceParams) error
	UpdateWorkbook(ctx context.Context, arg UpdateWorkbookParams) error
	UpsertUser(ctx context.Context, identityID string) (int64, error)
	WorkbookExists(ctx context.Context, id int64) (bool, error)
}

var _ Querier = (*Queries)(nil)
