// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package db

import (
	"context"
	"database/sql"
)

const countQuestions = `-- name: CountQuestions :one
SELECT COUNT(*) FROM questions
`

func (q *Queries) CountQuestions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuestions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChoice = `-- name: CreateChoice :exec
INSERT INTO questions_single_choice_choices (single_choice_id, choice_index, text, is_correct)
VALUES ($1, $2, $3, $4)
`

type CreateChoiceParams struct {
	SingleChoiceID int64  `json:"single_choice_id"`
	ChoiceIndex    int32  `json:"choice_index"`
	Text           string `json:"text"`
	IsCorrect      bool   `json:"is_correct"`
}

func (q *Queries) CreateChoice(ctx context.Context, arg CreateChoiceParams) error {
	_, err := q.db.ExecContext(ctx, createChoice,
		arg.SingleChoiceID,
		arg.ChoiceIndex,
		arg.Text,
		arg.IsCorrect,
	)
	return err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (type) VALUES ($1) RETURNING id
`

func (q *Queries) CreateQuestion(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, type_)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSingleChoice = `-- name: CreateSingleChoice :one
INSERT INTO questions_single_choice (question_id, text, explanation)
VALUES ($1, $2, $3) RETURNING id
`

type CreateSingleChoiceParams struct {
	QuestionID  int64          `json:"question_id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
}

func (q *Queries) CreateSingleChoice(ctx context.Context, arg CreateSingleChoiceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSingleChoice, arg.QuestionID, arg.Text, arg.Explanation)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteChoicesByQuestionID = `-- name: DeleteChoicesByQuestionID :exec
DELETE FROM questions_single_choice_choices
WHERE single_choice_id = (SELECT id FROM questions_single_choice WHERE question_id = $1)
`

func (q *Queries) DeleteChoicesByQuestionID(ctx context.Context, questionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteChoicesByQuestionID, questionID)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :execresult
DELETE FROM questions WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteQuestion, id)
}

const getChoicesByQuestionID = `-- name: GetChoicesByQuestionID :many
SELECT text, is_correct, choice_index
FROM questions_single_choice_choices
WHERE single_choice_id = (SELECT id FROM questions_single_choice WHERE question_id = $1)
ORDER BY choice_index
`

type GetChoicesByQuestionIDRow struct {
	Text        string `json:"text"`
	IsCorrect   bool   `json:"is_correct"`
	ChoiceIndex int32  `json:"choice_index"`
}

func (q *Queries) GetChoicesByQuestionID(ctx context.Context, questionID int64) ([]GetChoicesByQuestionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getChoicesByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChoicesByQuestionIDRow{}
	for rows.Next() {
		var i GetChoicesByQuestionIDRow
		if err := rows.Scan(&i.Text, &i.IsCorrect, &i.ChoiceIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT q.id, qsc.text, qsc.explanation
FROM questions q
JOIN questions_single_choice qsc ON q.id = qsc.question_id
WHERE q.id = $1
`

type GetQuestionByIDRow struct {
	ID          int64          `json:"id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
}

func (q *Queries) GetQuestionByID(ctx context.Context, id int64) (GetQuestionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByID, id)
	var i GetQuestionByIDRow
	err := row.Scan(&i.ID, &i.Text, &i.Explanation)
	return i, err
}

const getSingleChoiceID = `-- name: GetSingleChoiceID :one
SELECT id FROM questions_single_choice WHERE question_id = $1
`

func (q *Queries) GetSingleChoiceID(ctx context.Context, questionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSingleChoiceID, questionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listQuestions = `-- name: ListQuestions :many
SELECT q.id, qsc.text, qsc.explanation
FROM questions q
JOIN questions_single_choice qsc ON q.id = qsc.question_id
ORDER BY q.id
LIMIT $1 OFFSET $2
`

type ListQuestionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListQuestionsRow struct {
	ID          int64          `json:"id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
}

func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]ListQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuestions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionsRow{}
	for rows.Next() {
		var i ListQuestionsRow
		if err := rows.Scan(&i.ID, &i.Text, &i.Explanation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsWithChoices = `-- name: ListQuestionsWithChoices :many
SELECT q.id, qsc.text, qsc.explanation,
    c.text AS choice_text, c.is_correct, c.choice_index
FROM questions q
JOIN questions_single_choice qsc ON q.id = qsc.question_id
LEFT JOIN questions_single_choice_choices c ON c.single_choice_id = qsc.id
WHERE q.id IN (SELECT id FROM questions ORDER BY id LIMIT $1 OFFSET $2)
ORDER BY q.id, c.choice_index
`

type ListQuestionsWithChoicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListQuestionsWithChoicesRow struct {
	ID          int64          `json:"id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
	ChoiceText  sql.NullString `json:"choice_text"`
	IsCorrect   sql.NullBool   `json:"is_correct"`
	ChoiceIndex sql.NullInt32  `json:"choice_index"`
}

func (q *Queries) ListQuestionsWithChoices(ctx context.Context, arg ListQuestionsWithChoicesParams) ([]ListQuestionsWithChoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsWithChoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionsWithChoicesRow{}
	for rows.Next() {
		var i ListQuestionsWithChoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Explanation,
			&i.ChoiceText,
			&i.IsCorrect,
			&i.ChoiceIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const questionExists = `-- name: QuestionExists :one
SELECT EXISTS(SELECT 1 FROM questions WHERE id = $1)
`

func (q *Queries) QuestionExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, questionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateQuestionTimestamp = `-- name: UpdateQuestionTimestamp :exec
UPDATE questions SET updated_at = $1 WHERE id = $2
`

type UpdateQuestionTimestampParams struct {
	UpdatedAt sql.NullTime `json:"updated_at"`
	ID        int64        `json:"id"`
}

func (q *Queries) UpdateQuestionTimestamp(ctx context.Context, arg UpdateQuestionTimestampParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestionTimestamp, arg.UpdatedAt, arg.ID)
	return err
}

const updateSingleChoice = `-- name: UpdateSingleChoice :exec
UPDATE questions_single_choice
SET text = $1, explanation = $2, updated_at = $3
WHERE question_id = $4
`

type UpdateSingleChoiceParams struct {
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	QuestionID  int64          `json:"question_id"`
}

func (q *Queries) UpdateSingleChoice(ctx context.Context, arg UpdateSingleChoiceParams) error {
	_, err := q.db.ExecContext(ctx, updateSingleChoice,
		arg.Text,
		arg.Explanation,
		arg.UpdatedAt,
		arg.QuestionID,
	)
	return err
}
