// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package db

import (
	"context"
	"time"
)

const consumeTransferToken = `-- name: ConsumeTransferToken :one
UPDATE transfer_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE token = $1
  AND used_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
RETURNING identity_id
`

func (q *Queries) ConsumeTransferToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, consumeTransferToken, token)
	var identity_id string
	err := row.Scan(&identity_id)
	return identity_id, err
}

const createTransferToken = `-- name: CreateTransferToken :one
INSERT INTO transfer_tokens (token, identity_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, expires_at
`

type CreateTransferTokenParams struct {
	Token      string    `json:"token"`
	IdentityID string    `json:"identity_id"`
	ExpiresAt  time.Time `json:"expires_at"`
}

type CreateTransferTokenRow struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateTransferToken(ctx context.Context, arg CreateTransferTokenParams) (CreateTransferTokenRow, error) {
	row := q.db.QueryRowContext(ctx, createTransferToken, arg.Token, arg.IdentityID, arg.ExpiresAt)
	var i CreateTransferTokenRow
	err := row.Scan(&i.Token, &i.ExpiresAt)
	return i, err
}

const deleteTransferTokensByIdentityID = `-- name: DeleteTransferTokensByIdentityID :exec
DELETE FROM transfer_tokens WHERE identity_id = $1
`

func (q *Queries) DeleteTransferTokensByIdentityID(ctx context.Context, identityID string) error {
	_, err := q.db.ExecContext(ctx, deleteTransferTokensByIdentityID, identityID)
	return err
}

const getActiveTransferToken = `-- name: GetActiveTransferToken :one
SELECT token, expires_at FROM transfer_tokens
WHERE identity_id = $1
  AND used_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveTransferTokenRow struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetActiveTransferToken(ctx context.Context, identityID string) (GetActiveTransferTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveTransferToken, identityID)
	var i GetActiveTransferTokenRow
	err := row.Scan(&i.Token, &i.ExpiresAt)
	return i, err
}
