// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workbooks.sql

package db

import (
	"context"
	"database/sql"
)

const countWorkbooks = `-- name: CountWorkbooks :one
SELECT COUNT(*) FROM workbooks
`

func (q *Queries) CountWorkbooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkbooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkbook = `-- name: CreateWorkbook :one
INSERT INTO workbooks (title, description, category_id) VALUES ($1, $2, $3) RETURNING id
`

type CreateWorkbookParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CategoryID  sql.NullInt64  `json:"category_id"`
}

func (q *Queries) CreateWorkbook(ctx context.Context, arg CreateWorkbookParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createWorkbook, arg.Title, arg.Description, arg.CategoryID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createWorkbookQuestion = `-- name: CreateWorkbookQuestion :exec
INSERT INTO workbook_questions (workbook_id, question_id, order_index) VALUES ($1, $2, $3)
`

type CreateWorkbookQuestionParams struct {
	WorkbookID int64 `json:"workbook_id"`
	QuestionID int64 `json:"question_id"`
	OrderIndex int32 `json:"order_index"`
}

func (q *Queries) CreateWorkbookQuestion(ctx context.Context, arg CreateWorkbookQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createWorkbookQuestion, arg.WorkbookID, arg.QuestionID, arg.OrderIndex)
	return err
}

const deleteWorkbook = `-- name: DeleteWorkbook :execresult
DELETE FROM workbooks WHERE id = $1
`

func (q *Queries) DeleteWorkbook(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteWorkbook, id)
}

const deleteWorkbookQuestions = `-- name: DeleteWorkbookQuestions :exec
DELETE FROM workbook_questions WHERE workbook_id = $1
`

func (q *Queries) DeleteWorkbookQuestions(ctx context.Context, workbookID int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorkbookQuestions, workbookID)
	return err
}

const getWorkbookByID = `-- name: GetWorkbookByID :one
SELECT id, title, description, category_id FROM workbooks WHERE id = $1
`

type GetWorkbookByIDRow struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CategoryID  sql.NullInt64  `json:"category_id"`
}

func (q *Queries) GetWorkbookByID(ctx context.Context, id int64) (GetWorkbookByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkbookByID, id)
	var i GetWorkbookByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
	)
	return i, err
}

const getWorkbookTitle = `-- name: GetWorkbookTitle :one
SELECT title, description, category_id FROM workbooks WHERE id = $1
`

type GetWorkbookTitleRow struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CategoryID  sql.NullInt64  `json:"category_id"`
}

func (q *Queries) GetWorkbookTitle(ctx context.Context, id int64) (GetWorkbookTitleRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkbookTitle, id)
	var i GetWorkbookTitleRow
	err := row.Scan(&i.Title, &i.Description, &i.CategoryID)
	return i, err
}

const listAllWorkbooks = `-- name: ListAllWorkbooks :many
SELECT w.id, w.title, w.description, w.category_id,
    (SELECT COUNT(*) FROM workbook_questions wq WHERE wq.workbook_id = w.id) as question_count
FROM workbooks w
ORDER BY w.id
`

type ListAllWorkbooksRow struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	CategoryID    sql.NullInt64  `json:"category_id"`
	QuestionCount int64          `json:"question_count"`
}

func (q *Queries) ListAllWorkbooks(ctx context.Context) ([]ListAllWorkbooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkbooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllWorkbooksRow{}
	for rows.Next() {
		var i ListAllWorkbooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByWorkbook = `-- name: ListQuestionsByWorkbook :many
SELECT q.id, qsc.text, qsc.explanation
FROM questions q
JOIN questions_single_choice qsc ON q.id = qsc.question_id
JOIN workbook_questions wq ON q.id = wq.question_id
WHERE wq.workbook_id = $1
ORDER BY wq.order_index
`

type ListQuestionsByWorkbookRow struct {
	ID          int64          `json:"id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
}

func (q *Queries) ListQuestionsByWorkbook(ctx context.Context, workbookID int64) ([]ListQuestionsByWorkbookRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsByWorkbook, workbookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionsByWorkbookRow{}
	for rows.Next() {
		var i ListQuestionsByWorkbookRow
		if err := rows.Scan(&i.ID, &i.Text, &i.Explanation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsWithChoicesByWorkbook = `-- name: ListQuestionsWithChoicesByWorkbook :many
SELECT q.id, qsc.text, qsc.explanation,
    c.text AS choice_text, c.is_correct, c.choice_index
FROM questions q
JOIN questions_single_choice qsc ON q.id = qsc.question_id
JOIN workbook_questions wq ON q.id = wq.question_id
LEFT JOIN questions_single_choice_choices c ON c.single_choice_id = qsc.id
WHERE wq.workbook_id = $1
ORDER BY wq.order_index, c.choice_index
`

type ListQuestionsWithChoicesByWorkbookRow struct {
	ID          int64          `json:"id"`
	Text        string         `json:"text"`
	Explanation sql.NullString `json:"explanation"`
	ChoiceText  sql.NullString `json:"choice_text"`
	IsCorrect   sql.NullBool   `json:"is_correct"`
	ChoiceIndex sql.NullInt32  `json:"choice_index"`
}

func (q *Queries) ListQuestionsWithChoicesByWorkbook(ctx context.Context, workbookID int64) ([]ListQuestionsWithChoicesByWorkbookRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsWithChoicesByWorkbook, workbookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionsWithChoicesByWorkbookRow{}
	for rows.Next() {
		var i ListQuestionsWithChoicesByWorkbookRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Explanation,
			&i.ChoiceText,
			&i.IsCorrect,
			&i.ChoiceIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkbooks = `-- name: ListWorkbooks :many
SELECT w.id, w.title, w.description, w.category_id,
    (SELECT COUNT(*) FROM workbook_questions wq WHERE wq.workbook_id = w.id) as question_count
FROM workbooks w
ORDER BY w.id
LIMIT $1 OFFSET $2
`

type ListWorkbooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListWorkbooksRow struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	CategoryID    sql.NullInt64  `json:"category_id"`
	QuestionCount int64          `json:"question_count"`
}

func (q *Queries) ListWorkbooks(ctx context.Context, arg ListWorkbooksParams) ([]ListWorkbooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkbooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkbooksRow{}
	for rows.Next() {
		var i ListWorkbooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkbook = `-- name: UpdateWorkbook :exec
UPDATE workbooks SET title = $1, description = $2, category_id = $3, updated_at = $4 WHERE id = $5
`

type UpdateWorkbookParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CategoryID  sql.NullInt64  `json:"category_id"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateWorkbook(ctx context.Context, arg UpdateWorkbookParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkbook,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const workbookExists = `-- name: WorkbookExists :one
SELECT EXISTS(SELECT 1 FROM workbooks WHERE id = $1)
`

func (q *Queries) WorkbookExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, workbookExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
