name: iOS

on:
  push:
    branches: [ main ]
    paths:
      - 'ios/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ios/**'

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        working-directory: ./ios
        run: |
          xcodebuild build \
            -scheme Rikako \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO

      - name: Run tests
        working-directory: ./ios
        run: |
          xcodebuild test \
            -scheme Rikako \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro' \
            -skip-testing:RikakoUITests \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO
